<?php
return [
    'admin_title' => 'Zdarma Servery', 'admin_subtitle' => 'Nabídněte uživatelům zdarma servery', 'breadcrumb_admin' => 'Admin', 'breadcrumb_extensions' => 'Rozšíření', 'breadcrumb_freeservers' => 'Zdarma Servery',
    'stat_active_servers' => 'Aktivní Zdarma Servery', 'stat_users_with_servers' => 'Uživatelé se Zdarma Servery', 'stat_allowed_eggs' => 'Povolené Eggs', 'stat_system_status' => 'Stav Systému', 'status_on' => 'ZAPNUTO', 'status_off' => 'VYPNUTO',
    'stats_dashboard_title' => 'Přehled Statistik', 'stats_total_servers' => 'Celkem Serverů', 'stats_active_now' => 'Aktivní Nyní', 'stats_created_today' => 'Vytvořeno Dnes', 'stats_expiring_soon' => 'Brzy Vyprší (7d)', 'stats_resources' => 'Zdroje', 'stats_memory' => 'Paměť', 'stats_disk' => 'Disk', 'stats_avg_cpu' => 'Průměr CPU', 'stats_top_users' => 'Nej Uživatelé', 'stats_no_data' => 'Zatím žádná data',
    'section_settings' => 'Nastavení', 'setting_enable_system' => 'Povolit Zdarma Servery', 'setting_enabled' => 'Povoleno', 'setting_disabled' => 'Zakázáno', 'setting_max_servers' => 'Max. Serverů na Uživatele', 'setting_description' => 'Popis Serveru', 'setting_description_placeholder' => 'Zdarma Server vytvořen pomocí Free Servers Extension', 'setting_description_help' => 'Tento popis bude použit pro každý vytvořený zdarma server.', 'setting_display_unit' => 'Jednotka Zobrazení Zdrojů', 'setting_display_unit_mb' => 'MB (Megabajt)', 'setting_display_unit_gb' => 'GB (Gigabajt)', 'setting_display_unit_help' => 'Vyberte, jak se uživatelům zobrazuje paměť a disk.', 'setting_language' => 'Jazyk / Language', 'setting_language_help' => 'Vyberte jazyk rozhraní pro všechny uživatele (podpora 17 evropských jazyků).',
    'section_expiration' => 'Vypršení a Prodloužení Serveru', 'setting_expiration_days' => 'Dny Vypršení', 'setting_expiration_days_help' => 'Dny do vypršení serveru (0 = nikdy nevyprší)', 'setting_extension_days' => 'Dny Prodloužení', 'setting_extension_days_help' => 'Dny přidané když uživatel prodlouží server', 'setting_allow_extension' => 'Povolit Uživatelská Prodloužení', 'setting_allow_extension_help' => 'Uživatelé mohou prodloužit datum vypršení', 'yes' => 'Ano', 'no' => 'Ne',
    'section_stats' => 'Statistiky Panelu Admina', 'setting_enable_stats' => 'Povolit Přehled Statistik', 'setting_enable_stats_help' => 'Zobrazit přehled statistik v panelu admina',
    'section_discord' => 'Integrace Discord Webhook', 'setting_discord_webhook' => 'Discord Webhook URL', 'setting_discord_webhook_placeholder' => 'https://discord.com/api/webhooks/...', 'setting_discord_webhook_help' => 'Nechte prázdné pro vypnutí Discord oznámení', 'setting_discord_create' => 'Oznámit při Vytvoření Serveru', 'setting_discord_delete' => 'Oznámit při Smazání Serveru', 'setting_discord_expire' => 'Oznámit při Vypršení Serveru',
    'section_resources' => 'Výchozí Zdroje', 'resource_ram' => 'RAM (MB)', 'resource_disk' => 'Disk (MB)', 'resource_cpu' => 'CPU (%)', 'resource_swap' => 'Swap (MB)', 'resource_io' => 'Block IO', 'resource_databases' => 'Databáze', 'resource_ports' => 'Porty', 'resource_backups' => 'Zálohy',
    'section_nodes' => 'Povolené Nodes', 'nodes_help' => 'Pokud nejsou vybrány žádné nodes, jsou povoleny všechny nodes.', 'nodes_none' => 'Žádné nodes k dispozici.',
    'btn_save' => 'Uložit Nastavení', 'btn_add' => 'Přidat', 'btn_enable' => 'Povolit', 'btn_disable' => 'Zakázat', 'btn_remove' => 'Odebrat',
    'section_eggs' => 'Povolené Eggs', 'egg_select' => '-- Vyberte Egg --', 'egg_custom_name' => 'Vlastní Název', 'egg_status_active' => 'Aktivní', 'egg_status_disabled' => 'Zakázáno', 'eggs_none' => 'Zatím nepřidány žádné eggs. Přidejte eggs výše, aby byly k dispozici pro zdarma servery.', 'eggs_confirm_remove' => 'Opravdu odebrat tento egg?',
    'section_user_limits' => 'Limity na Uživatele', 'user_limits_help' => 'Nastavte vlastní limity serverů pro jednotlivé uživatele. Uživatelé bez vlastního limitu používají globální limit (%s).', 'user_search' => 'Hledat Uživatele', 'user_search_placeholder' => 'Hledat podle uživatelského jména nebo emailu...', 'user_selected' => 'Vybraný Uživatel', 'user_no_selected' => 'Žádný uživatel nevybrán', 'user_max_servers' => 'Max. Serverů', 'user_add_limit' => 'Přidat Limit', 'table_username' => 'Uživatelské Jméno', 'table_email' => 'Email', 'table_max_servers' => 'Max. Serverů', 'table_current' => 'Aktuální', 'table_status' => 'Stav', 'table_actions' => 'Akce', 'status_blocked' => 'Blokován', 'status_at_limit' => 'Na Limitu', 'status_can_create' => 'Může Vytvořit', 'user_limits_none' => 'Nejsou nastaveny žádné vlastní limity uživatelů. Všichni uživatelé používají globální limit <strong>%s</strong> serverů.', 'user_has_limit' => 'Má Limit', 'user_limit_confirm_remove' => 'Odebrat vlastní limit pro %s? Budou používat globální limit.', 'user_search_no_results' => 'Žádní uživatelé nenalezeni', 'user_search_error' => 'Chyba při hledání uživatelů', 'user_select_first' => 'Prosím vyberte nejprve uživatele!',
    'alert_db_error' => 'Tabulky databáze nenalezeny. Prosím spusťte: php artisan migrate', 'alert_settings_error' => 'Nastavení se nepodařilo načíst. Prosím obnovte stránku.', 'msg_success_save' => 'Nastavení úspěšně uloženo!', 'msg_error_unknown' => 'Neznámá akce.', 'msg_error_select_egg' => 'Prosím vyberte egg!', 'msg_error_egg_exists' => 'Egg již existuje!', 'msg_success_egg_add' => 'Egg úspěšně přidán!', 'msg_success_status' => 'Stav změněn!', 'msg_success_egg_remove' => 'Egg úspěšně odebrán!', 'msg_error_select_user' => 'Prosím vyberte uživatele!', 'msg_error_negative' => 'Maximum serverů nemůže být záporné!', 'msg_error_user_not_found' => 'Uživatel nenalezen!', 'msg_error_limit_exists' => 'Uživatel již má vlastní limit!', 'msg_success_limit_set' => 'Vlastní limit nastaven pro %s!', 'msg_error_limit_not_found' => 'Limit nenalezen!', 'msg_success_limit_update' => 'Limit úspěšně aktualizován!', 'msg_success_limit_remove' => '%s nyní používá globální limit.',
    'api_disabled' => 'Zdarma servery jsou momentálně zakázány.', 'api_tables_missing' => 'Tabulky Free Servers nenalezeny. Prosím spusťte php artisan migrate.', 'api_egg_not_available' => 'Tento egg není k dispozici pro zdarma servery.', 'api_node_not_available' => 'Tento node není k dispozici pro zdarma servery.', 'api_limit_reached' => 'Již jste dosáhli maximálního počtu zdarma serverů.', 'api_no_ports' => 'Žádné volné porty k dispozici na tomto node.', 'api_no_docker' => 'Pro tento egg není nakonfigurován žádný Docker obraz. Prosím kontaktujte správce.', 'api_success_create' => 'Server úspěšně vytvořen!', 'api_port_taken' => 'Vybraný port byl obsazen. Prosím zkuste to znovu.', 'api_error_create' => 'Chyba při vytváření serveru: %s', 'api_extension_disabled' => 'Prodloužení serveru není povoleno.', 'api_server_not_found' => 'Server nenalezen nebo vám nepatří.', 'api_success_extend' => 'Server úspěšně prodloužen!',
];
