<?php
return [
    'admin_title' => 'Gratis Servere', 'admin_subtitle' => 'Tilbyd brugere gratis servere', 'breadcrumb_admin' => 'Admin', 'breadcrumb_extensions' => 'Udvidelser', 'breadcrumb_freeservers' => 'Gratis Servere',
    'stat_active_servers' => 'Aktive Gratis Servere', 'stat_users_with_servers' => 'Brugere med Gratis Servere', 'stat_allowed_eggs' => 'Tilladte Eggs', 'stat_system_status' => 'Systemstatus', 'status_on' => 'TIL', 'status_off' => 'FRA',
    'stats_dashboard_title' => 'Statistikoversigt', 'stats_total_servers' => 'Servere i Alt', 'stats_active_now' => 'Aktive Nu', 'stats_created_today' => 'Oprettet I Dag', 'stats_expiring_soon' => 'Udløber Snart (7d)', 'stats_resources' => 'Ressourcer', 'stats_memory' => 'Hukommelse', 'stats_disk' => 'Disk', 'stats_avg_cpu' => 'Gns. CPU', 'stats_top_users' => 'Top Brugere', 'stats_no_data' => 'Ingen data endnu',
    'section_settings' => 'Indstillinger', 'setting_enable_system' => 'Aktiver Gratis Servere', 'setting_enabled' => 'Aktiveret', 'setting_disabled' => 'Deaktiveret', 'setting_max_servers' => 'Maks. Servere pr. Bruger', 'setting_description' => 'Serverbeskrivelse', 'setting_description_placeholder' => 'Gratis Server oprettet via Free Servers Extension', 'setting_description_help' => 'Denne beskrivelse vil blive brugt til hver oprettet gratis server.', 'setting_display_unit' => 'Ressourcevisningsenhed', 'setting_display_unit_mb' => 'MB (Megabyte)', 'setting_display_unit_gb' => 'GB (Gigabyte)', 'setting_display_unit_help' => 'Vælg hvordan hukommelse og disk vises til brugere.', 'setting_language' => 'Sprog / Language', 'setting_language_help' => 'Vælg grænsefladsproget for alle brugere (17 europæiske sprog understøttes).',
    'section_expiration' => 'Serverudløb og Forlængelser', 'setting_expiration_days' => 'Udløbsdage', 'setting_expiration_days_help' => 'Dage til serveren udløber (0 = udløber aldrig)', 'setting_extension_days' => 'Forlængelsesdage', 'setting_extension_days_help' => 'Dage tilføjet når brugeren forlænger serveren', 'setting_allow_extension' => 'Tillad Brugerforlængelser', 'setting_allow_extension_help' => 'Brugere kan forlænge udløbsdatoen', 'yes' => 'Ja', 'no' => 'Nej',
    'section_stats' => 'Admin-panelstatistik', 'setting_enable_stats' => 'Aktiver Statistikoversigt', 'setting_enable_stats_help' => 'Vis statistikoversigt i admin-panelet',
    'section_discord' => 'Discord Webhook-integration', 'setting_discord_webhook' => 'Discord Webhook URL', 'setting_discord_webhook_placeholder' => 'https://discord.com/api/webhooks/...', 'setting_discord_webhook_help' => 'Lad stå tom for at deaktivere Discord-notifikationer', 'setting_discord_create' => 'Notificer ved Serveroprettelse', 'setting_discord_delete' => 'Notificer ved Serversletning', 'setting_discord_expire' => 'Notificer ved Serverudløb',
    'section_resources' => 'Standardressourcer', 'resource_ram' => 'RAM (MB)', 'resource_disk' => 'Disk (MB)', 'resource_cpu' => 'CPU (%)', 'resource_swap' => 'Swap (MB)', 'resource_io' => 'Block IO', 'resource_databases' => 'Databaser', 'resource_ports' => 'Porte', 'resource_backups' => 'Sikkerhedskopier',
    'section_nodes' => 'Tilladte Noder', 'nodes_help' => 'Hvis ingen noder er valgt, er alle noder tilladt.', 'nodes_none' => 'Ingen noder tilgængelige.',
    'btn_save' => 'Gem Indstillinger', 'btn_add' => 'Tilføj', 'btn_enable' => 'Aktiver', 'btn_disable' => 'Deaktiver', 'btn_remove' => 'Fjern',
    'section_eggs' => 'Tilladte Eggs', 'egg_select' => '-- Vælg Egg --', 'egg_custom_name' => 'Brugerdefineret Navn', 'egg_status_active' => 'Aktiv', 'egg_status_disabled' => 'Deaktiveret', 'eggs_none' => 'Ingen eggs tilføjet endnu. Tilføj eggs ovenfor for at gøre dem tilgængelige for gratis servere.', 'eggs_confirm_remove' => 'Vil du virkelig fjerne dette egg?',
    'section_user_limits' => 'Grænser pr. Bruger', 'user_limits_help' => 'Indstil brugerdefinerede servergrænser for individuelle brugere. Brugere uden brugerdefineret grænse bruger den globale grænse (%s).', 'user_search' => 'Søg Bruger', 'user_search_placeholder' => 'Søg efter brugernavn eller e-mail...', 'user_selected' => 'Valgt Bruger', 'user_no_selected' => 'Ingen bruger valgt', 'user_max_servers' => 'Maks. Servere', 'user_add_limit' => 'Tilføj Grænse', 'table_username' => 'Brugernavn', 'table_email' => 'E-mail', 'table_max_servers' => 'Maks. Servere', 'table_current' => 'Nuværende', 'table_status' => 'Status', 'table_actions' => 'Handlinger', 'status_blocked' => 'Blokeret', 'status_at_limit' => 'Ved Grænsen', 'status_can_create' => 'Kan Oprette', 'user_limits_none' => 'Ingen brugerdefinerede brugergrænser angivet. Alle brugere bruger den globale grænse på <strong>%s</strong> servere.', 'user_has_limit' => 'Har Grænse', 'user_limit_confirm_remove' => 'Fjern brugerdefineret grænse for %s? De vil bruge den globale grænse.', 'user_search_no_results' => 'Ingen brugere fundet', 'user_search_error' => 'Fejl ved søgning efter brugere', 'user_select_first' => 'Vælg venligst en bruger først!',
    'alert_db_error' => 'Databasetabeller ikke fundet. Kør venligst: php artisan migrate', 'alert_settings_error' => 'Indstillinger kunne ikke indlæses. Genindlæs venligst siden.', 'msg_success_save' => 'Indstillinger gemt!', 'msg_error_unknown' => 'Ukendt handling.', 'msg_error_select_egg' => 'Vælg venligst et egg!', 'msg_error_egg_exists' => 'Egg eksisterer allerede!', 'msg_success_egg_add' => 'Egg tilføjet!', 'msg_success_status' => 'Status ændret!', 'msg_success_egg_remove' => 'Egg fjernet!', 'msg_error_select_user' => 'Vælg venligst en bruger!', 'msg_error_negative' => 'Maksimalt antal servere kan ikke være negativt!', 'msg_error_user_not_found' => 'Bruger ikke fundet!', 'msg_error_limit_exists' => 'Brugeren har allerede en brugerdefineret grænse!', 'msg_success_limit_set' => 'Brugerdefineret grænse sat for %s!', 'msg_error_limit_not_found' => 'Grænse ikke fundet!', 'msg_success_limit_update' => 'Grænse opdateret!', 'msg_success_limit_remove' => '%s bruger nu den globale grænse.',
    'api_disabled' => 'Gratis servere er i øjeblikket deaktiveret.', 'api_tables_missing' => 'Free Servers-tabeller ikke fundet. Kør venligst php artisan migrate.', 'api_egg_not_available' => 'Dette egg er ikke tilgængeligt for gratis servere.', 'api_node_not_available' => 'Denne node er ikke tilgængelig for gratis servere.', 'api_limit_reached' => 'Du har allerede nået det maksimale antal gratis servere.', 'api_no_ports' => 'Ingen ledige porte tilgængelige på denne node.', 'api_no_docker' => 'Intet Docker-image konfigureret for dette egg. Kontakt venligst en administrator.', 'api_success_create' => 'Server oprettet!', 'api_port_taken' => 'Den valgte port blev taget. Prøv venligst igen.', 'api_error_create' => 'Fejl ved oprettelse af server: %s', 'api_extension_disabled' => 'Serverforlængelse er ikke tilladt.', 'api_server_not_found' => 'Server ikke fundet eller tilhører ikke dig.', 'api_success_extend' => 'Server forlænget!',
];
