<?php
return [
    'admin_title' => 'Δωρεάν Διακομιστές', 'admin_subtitle' => 'Προσφορά δωρεάν διακομιστών στους χρήστες', 'breadcrumb_admin' => 'Διαχειριστής', 'breadcrumb_extensions' => 'Επεκτάσεις', 'breadcrumb_freeservers' => 'Δωρεάν Διακομιστές',
    'stat_active_servers' => 'Ενεργοί Δωρεάν Διακομιστές', 'stat_users_with_servers' => 'Χρήστες με Δωρεάν Διακομιστές', 'stat_allowed_eggs' => 'Επιτρεπόμενα Eggs', 'stat_system_status' => 'Κατάσταση Συστήματος', 'status_on' => 'ΕΝΕΡΓΟ', 'status_off' => 'ΑΝΕΝΕΡΓΟ',
    'stats_dashboard_title' => 'Πίνακας Στατιστικών', 'stats_total_servers' => 'Σύνολο Διακομιστών', 'stats_active_now' => 'Ενεργοί Τώρα', 'stats_created_today' => 'Δημιουργήθηκαν Σήμερα', 'stats_expiring_soon' => 'Λήγουν Σύντομα (7η)', 'stats_resources' => 'Πόροι', 'stats_memory' => 'Μνήμη', 'stats_disk' => 'Δίσκος', 'stats_avg_cpu' => 'Μέσος CPU', 'stats_top_users' => 'Κορυφαίοι Χρήστες', 'stats_no_data' => 'Δεν υπάρχουν δεδομένα ακόμα',
    'section_settings' => 'Ρυθμίσεις', 'setting_enable_system' => 'Ενεργοποίηση Δωρεάν Διακομιστών', 'setting_enabled' => 'Ενεργοποιημένο', 'setting_disabled' => 'Απενεργοποιημένο', 'setting_max_servers' => 'Μέγ. Διακομιστές ανά Χρήστη', 'setting_description' => 'Περιγραφή Διακομιστή', 'setting_description_placeholder' => 'Δωρεάν Διακομιστής δημιουργήθηκε μέσω Free Servers Extension', 'setting_description_help' => 'Αυτή η περιγραφή θα χρησιμοποιηθεί για κάθε δωρεάν διακομιστή που δημιουργείται.', 'setting_display_unit' => 'Μονάδα Εμφάνισης Πόρων', 'setting_display_unit_mb' => 'MB (Megabyte)', 'setting_display_unit_gb' => 'GB (Gigabyte)', 'setting_display_unit_help' => 'Επιλέξτε πώς εμφανίζεται η μνήμη και ο δίσκος στους χρήστες.', 'setting_language' => 'Γλώσσα / Language', 'setting_language_help' => 'Επιλέξτε τη γλώσσα διεπαφής για όλους τους χρήστες (υποστήριξη 17 ευρωπαϊκών γλωσσών).',
    'section_expiration' => 'Λήξη και Παρατάσεις Διακομιστή', 'setting_expiration_days' => 'Ημέρες Λήξης', 'setting_expiration_days_help' => 'Ημέρες μέχρι τη λήξη του διακομιστή (0 = δεν λήγει ποτέ)', 'setting_extension_days' => 'Ημέρες Παράτασης', 'setting_extension_days_help' => 'Ημέρες που προστίθενται όταν ο χρήστης παρατείνει τον διακομιστή', 'setting_allow_extension' => 'Να Επιτρέπονται Παρατάσεις Χρηστών', 'setting_allow_extension_help' => 'Οι χρήστες μπορούν να παρατείνουν την ημερομηνία λήξης', 'yes' => 'Ναι', 'no' => 'Όχι',
    'section_stats' => 'Στατιστικά Πίνακα Διαχειριστή', 'setting_enable_stats' => 'Ενεργοποίηση Πίνακα Στατιστικών', 'setting_enable_stats_help' => 'Εμφάνιση πίνακα στατιστικών στον πίνακα διαχειριστή',
    'section_discord' => 'Ενσωμάτωση Discord Webhook', 'setting_discord_webhook' => 'URL Discord Webhook', 'setting_discord_webhook_placeholder' => 'https://discord.com/api/webhooks/...', 'setting_discord_webhook_help' => 'Αφήστε κενό για απενεργοποίηση ειδοποιήσεων Discord', 'setting_discord_create' => 'Ειδοποίηση στη Δημιουργία Διακομιστή', 'setting_discord_delete' => 'Ειδοποίηση στη Διαγραφή Διακομιστή', 'setting_discord_expire' => 'Ειδοποίηση στη Λήξη Διακομιστή',
    'section_resources' => 'Προεπιλεγμένοι Πόροι', 'resource_ram' => 'RAM (MB)', 'resource_disk' => 'Δίσκος (MB)', 'resource_cpu' => 'CPU (%)', 'resource_swap' => 'Swap (MB)', 'resource_io' => 'Block IO', 'resource_databases' => 'Βάσεις Δεδομένων', 'resource_ports' => 'Θύρες', 'resource_backups' => 'Αντίγραφα Ασφαλείας',
    'section_nodes' => 'Επιτρεπόμενοι Κόμβοι', 'nodes_help' => 'Εάν δεν επιλεγούν κόμβοι, επιτρέπονται όλοι οι κόμβοι.', 'nodes_none' => 'Δεν υπάρχουν διαθέσιμοι κόμβοι.',
    'btn_save' => 'Αποθήκευση Ρυθμίσεων', 'btn_add' => 'Προσθήκη', 'btn_enable' => 'Ενεργοποίηση', 'btn_disable' => 'Απενεργοποίηση', 'btn_remove' => 'Αφαίρεση',
    'section_eggs' => 'Επιτρεπόμενα Eggs', 'egg_select' => '-- Επιλογή Egg --', 'egg_custom_name' => 'Προσαρμοσμένο Όνομα', 'egg_status_active' => 'Ενεργό', 'egg_status_disabled' => 'Απενεργοποιημένο', 'eggs_none' => 'Δεν έχουν προστεθεί eggs ακόμα. Προσθέστε eggs παραπάνω για να τα κάνετε διαθέσιμα για δωρεάν διακομιστές.', 'eggs_confirm_remove' => 'Να αφαιρεθεί αυτό το egg;',
    'section_user_limits' => 'Όρια ανά Χρήστη', 'user_limits_help' => 'Ορίστε προσαρμοσμένα όρια διακομιστών για μεμονωμένους χρήστες. Χρήστες χωρίς προσαρμοσμένο όριο χρησιμοποιούν το καθολικό όριο (%s).', 'user_search' => 'Αναζήτηση Χρήστη', 'user_search_placeholder' => 'Αναζήτηση με όνομα χρήστη ή email...', 'user_selected' => 'Επιλεγμένος Χρήστης', 'user_no_selected' => 'Δεν επιλέχθηκε χρήστης', 'user_max_servers' => 'Μέγ. Διακομιστές', 'user_add_limit' => 'Προσθήκη Ορίου', 'table_username' => 'Όνομα Χρήστη', 'table_email' => 'Email', 'table_max_servers' => 'Μέγ. Διακομιστές', 'table_current' => 'Τρέχον', 'table_status' => 'Κατάσταση', 'table_actions' => 'Ενέργειες', 'status_blocked' => 'Αποκλεισμένος', 'status_at_limit' => 'Στο Όριο', 'status_can_create' => 'Μπορεί να Δημιουργήσει', 'user_limits_none' => 'Δεν έχουν οριστεί προσαρμοσμένα όρια χρηστών. Όλοι οι χρήστες χρησιμοποιούν το καθολικό όριο των <strong>%s</strong> διακομιστών.', 'user_has_limit' => 'Έχει Όριο', 'user_limit_confirm_remove' => 'Αφαίρεση προσαρμοσμένου ορίου για %s; Θα χρησιμοποιήσουν το καθολικό όριο.', 'user_search_no_results' => 'Δεν βρέθηκαν χρήστες', 'user_search_error' => 'Σφάλμα κατά την αναζήτηση χρηστών', 'user_select_first' => 'Παρακαλώ επιλέξτε πρώτα έναν χρήστη!',
    'alert_db_error' => 'Δεν βρέθηκαν πίνακες βάσης δεδομένων. Παρακαλώ εκτελέστε: php artisan migrate', 'alert_settings_error' => 'Δεν ήταν δυνατή η φόρτωση των ρυθμίσεων. Παρακαλώ ανανεώστε τη σελίδα.', 'msg_success_save' => 'Ρυθμίσεις αποθηκεύτηκαν επιτυχώς!', 'msg_error_unknown' => 'Άγνωστη ενέργεια.', 'msg_error_select_egg' => 'Παρακαλώ επιλέξτε ένα egg!', 'msg_error_egg_exists' => 'Το egg υπάρχει ήδη!', 'msg_success_egg_add' => 'Egg προστέθηκε επιτυχώς!', 'msg_success_status' => 'Κατάσταση άλλαξε!', 'msg_success_egg_remove' => 'Egg αφαιρέθηκε επιτυχώς!', 'msg_error_select_user' => 'Παρακαλώ επιλέξτε χρήστη!', 'msg_error_negative' => 'Ο μέγιστος αριθμός διακομιστών δεν μπορεί να είναι αρνητικός!', 'msg_error_user_not_found' => 'Ο χρήστης δεν βρέθηκε!', 'msg_error_limit_exists' => 'Ο χρήστης έχει ήδη προσαρμοσμένο όριο!', 'msg_success_limit_set' => 'Προσαρμοσμένο όριο ορίστηκε για %s!', 'msg_error_limit_not_found' => 'Το όριο δεν βρέθηκε!', 'msg_success_limit_update' => 'Το όριο ενημερώθηκε επιτυχώς!', 'msg_success_limit_remove' => 'Ο %s χρησιμοποιεί τώρα το καθολικό όριο.',
    'api_disabled' => 'Οι δωρεάν διακομιστές είναι απενεργοποιημένοι αυτή τη στιγμή.', 'api_tables_missing' => 'Δεν βρέθηκαν πίνακες Free Servers. Παρακαλώ εκτελέστε php artisan migrate.', 'api_egg_not_available' => 'Αυτό το egg δεν είναι διαθέσιμο για δωρεάν διακομιστές.', 'api_node_not_available' => 'Αυτός ο κόμβος δεν είναι διαθέσιμος για δωρεάν διακομιστές.', 'api_limit_reached' => 'Έχετε ήδη φτάσει τον μέγιστο αριθμό δωρεάν διακομιστών.', 'api_no_ports' => 'Δεν υπάρχουν ελεύθερες θύρες σε αυτόν τον κόμβο.', 'api_no_docker' => 'Δεν έχει διαμορφωθεί εικόνα Docker για αυτό το egg. Παρακαλώ επικοινωνήστε με έναν διαχειριστή.', 'api_success_create' => 'Ο διακομιστής δημιουργήθηκε επιτυχώς!', 'api_port_taken' => 'Η επιλεγμένη θύρα ελήφθη. Παρακαλώ δοκιμάστε ξανά.', 'api_error_create' => 'Σφάλμα κατά τη δημιουργία διακομιστή: %s', 'api_extension_disabled' => 'Η παράταση διακομιστή δεν επιτρέπεται.', 'api_server_not_found' => 'Ο διακομιστής δεν βρέθηκε ή δεν σας ανήκει.', 'api_success_extend' => 'Ο διακομιστής παρατάθηκε επιτυχώς!',
];
