<?php
return [
    'admin_title' => 'Servidores Gratuitos', 'admin_subtitle' => 'Ofrecer servidores gratuitos a los usuarios', 'breadcrumb_admin' => 'Admin', 'breadcrumb_extensions' => 'Extensiones', 'breadcrumb_freeservers' => 'Servidores Gratuitos',
    'stat_active_servers' => 'Servidores Gratuitos Activos', 'stat_users_with_servers' => 'Usuarios con Servidores Gratuitos', 'stat_allowed_eggs' => 'Eggs Permitidos', 'stat_system_status' => 'Estado del Sistema', 'status_on' => 'ENCENDIDO', 'status_off' => 'APAGADO',
    'stats_dashboard_title' => 'Panel de Estadísticas', 'stats_total_servers' => 'Servidores Totales', 'stats_active_now' => 'Activos Ahora', 'stats_created_today' => 'Creados Hoy', 'stats_expiring_soon' => 'Expira Pronto (7d)', 'stats_resources' => 'Recursos', 'stats_memory' => 'Memoria', 'stats_disk' => 'Disco', 'stats_avg_cpu' => 'CPU Promedio', 'stats_top_users' => 'Mejores Usuarios', 'stats_no_data' => 'Aún sin datos',
    'section_settings' => 'Configuración', 'setting_enable_system' => 'Activar Servidores Gratuitos', 'setting_enabled' => 'Activado', 'setting_disabled' => 'Desactivado', 'setting_max_servers' => 'Máx. Servidores por Usuario', 'setting_description' => 'Descripción del Servidor', 'setting_description_placeholder' => 'Servidor Gratuito creado vía Free Servers Extension', 'setting_description_help' => 'Esta descripción se utilizará para cada servidor gratuito creado.', 'setting_display_unit' => 'Unidad de Visualización de Recursos', 'setting_display_unit_mb' => 'MB (Megabyte)', 'setting_display_unit_gb' => 'GB (Gigabyte)', 'setting_display_unit_help' => 'Elija cómo se muestran la memoria y el disco a los usuarios.', 'setting_language' => 'Idioma / Language', 'setting_language_help' => 'Elija el idioma de la interfaz para todos los usuarios (17 idiomas europeos soportados).',
    'section_expiration' => 'Vencimiento y Extensiones de Servidor', 'setting_expiration_days' => 'Días de Vencimiento', 'setting_expiration_days_help' => 'Días hasta que el servidor expire (0 = nunca expira)', 'setting_extension_days' => 'Días de Extensión', 'setting_extension_days_help' => 'Días añadidos cuando el usuario extiende el servidor', 'setting_allow_extension' => 'Permitir Extensiones de Usuario', 'setting_allow_extension_help' => 'Los usuarios pueden extender la fecha de vencimiento', 'yes' => 'Sí', 'no' => 'No',
    'section_stats' => 'Estadísticas del Panel de Admin', 'setting_enable_stats' => 'Activar Panel de Estadísticas', 'setting_enable_stats_help' => 'Mostrar panel de estadísticas en el panel de admin',
    'section_discord' => 'Integración de Webhook Discord', 'setting_discord_webhook' => 'URL Webhook Discord', 'setting_discord_webhook_placeholder' => 'https://discord.com/api/webhooks/...', 'setting_discord_webhook_help' => 'Dejar vacío para desactivar notificaciones Discord', 'setting_discord_create' => 'Notificar en Creación de Servidor', 'setting_discord_delete' => 'Notificar en Eliminación de Servidor', 'setting_discord_expire' => 'Notificar en Vencimiento de Servidor',
    'section_resources' => 'Recursos Predeterminados', 'resource_ram' => 'RAM (MB)', 'resource_disk' => 'Disco (MB)', 'resource_cpu' => 'CPU (%)', 'resource_swap' => 'Swap (MB)', 'resource_io' => 'Block IO', 'resource_databases' => 'Bases de Datos', 'resource_ports' => 'Puertos', 'resource_backups' => 'Copias de Seguridad',
    'section_nodes' => 'Nodos Permitidos', 'nodes_help' => 'Si no se selecciona ningún nodo, todos los nodos están permitidos.', 'nodes_none' => 'No hay nodos disponibles.',
    'btn_save' => 'Guardar Configuración', 'btn_add' => 'Añadir', 'btn_enable' => 'Activar', 'btn_disable' => 'Desactivar', 'btn_remove' => 'Eliminar',
    'section_eggs' => 'Eggs Permitidos', 'egg_select' => '-- Seleccionar Egg --', 'egg_custom_name' => 'Nombre Personalizado', 'egg_status_active' => 'Activo', 'egg_status_disabled' => 'Desactivado', 'eggs_none' => 'Aún no se han añadido eggs. Añade eggs arriba para que estén disponibles para servidores gratuitos.', 'eggs_confirm_remove' => '¿Realmente eliminar este egg?',
    'section_user_limits' => 'Límites por Usuario', 'user_limits_help' => 'Establecer límites de servidor personalizados para usuarios individuales. Los usuarios sin límite personalizado usan el límite global (%s).', 'user_search' => 'Buscar Usuario', 'user_search_placeholder' => 'Buscar por nombre de usuario o correo...', 'user_selected' => 'Usuario Seleccionado', 'user_no_selected' => 'Ningún usuario seleccionado', 'user_max_servers' => 'Máx. Servidores', 'user_add_limit' => 'Añadir Límite', 'table_username' => 'Nombre de Usuario', 'table_email' => 'Correo', 'table_max_servers' => 'Máx. Servidores', 'table_current' => 'Actual', 'table_status' => 'Estado', 'table_actions' => 'Acciones', 'status_blocked' => 'Bloqueado', 'status_at_limit' => 'En el Límite', 'status_can_create' => 'Puede Crear', 'user_limits_none' => 'No hay límites de usuario personalizados establecidos. Todos los usuarios usan el límite global de <strong>%s</strong> servidores.', 'user_has_limit' => 'Tiene Límite', 'user_limit_confirm_remove' => '¿Eliminar límite personalizado para %s? Usarán el límite global.', 'user_search_no_results' => 'No se encontraron usuarios', 'user_search_error' => 'Error al buscar usuarios', 'user_select_first' => '¡Por favor selecciona primero un usuario!',
    'alert_db_error' => 'Tablas de base de datos no encontradas. Por favor ejecute: php artisan migrate', 'alert_settings_error' => 'No se pudieron cargar los ajustes. Por favor recargue la página.', 'msg_success_save' => '¡Configuración guardada exitosamente!', 'msg_error_unknown' => 'Acción desconocida.', 'msg_error_select_egg' => '¡Por favor selecciona un egg!', 'msg_error_egg_exists' => '¡El egg ya existe!', 'msg_success_egg_add' => '¡Egg añadido exitosamente!', 'msg_success_status' => '¡Estado cambiado!', 'msg_success_egg_remove' => '¡Egg eliminado exitosamente!', 'msg_error_select_user' => '¡Por favor selecciona un usuario!', 'msg_error_negative' => '¡El máximo de servidores no puede ser negativo!', 'msg_error_user_not_found' => '¡Usuario no encontrado!', 'msg_error_limit_exists' => '¡El usuario ya tiene un límite personalizado!', 'msg_success_limit_set' => '¡Límite personalizado establecido para %s!', 'msg_error_limit_not_found' => '¡Límite no encontrado!', 'msg_success_limit_update' => '¡Límite actualizado exitosamente!', 'msg_success_limit_remove' => '%s ahora usa el límite global.',
    'api_disabled' => 'Los servidores gratuitos están actualmente desactivados.', 'api_tables_missing' => 'Tablas de Free Servers no encontradas. Por favor ejecute php artisan migrate.', 'api_egg_not_available' => 'Este egg no está disponible para servidores gratuitos.', 'api_node_not_available' => 'Este nodo no está disponible para servidores gratuitos.', 'api_limit_reached' => 'Ya has alcanzado el número máximo de servidores gratuitos.', 'api_no_ports' => 'No hay puertos libres disponibles en este nodo.', 'api_no_docker' => 'No hay imagen Docker configurada para este egg. Por favor contacta con un administrador.', 'api_success_create' => '¡Servidor creado exitosamente!', 'api_port_taken' => 'El puerto seleccionado fue tomado. Por favor inténtalo de nuevo.', 'api_error_create' => 'Error al crear el servidor: %s', 'api_extension_disabled' => 'La extensión de servidor no está permitida.', 'api_server_not_found' => 'Servidor no encontrado o no es tuyo.', 'api_success_extend' => '¡Servidor extendido exitosamente!',
];
