<?php
return [
    'admin_title' => 'Ilmaiset Palvelimet', 'admin_subtitle' => 'Tarjoa käyttäjille ilmaisia palvelimia', 'breadcrumb_admin' => 'Admin', 'breadcrumb_extensions' => 'Laajennukset', 'breadcrumb_freeservers' => 'Ilmaiset Palvelimet',
    'stat_active_servers' => 'Aktiiviset Ilmaiset Palvelimet', 'stat_users_with_servers' => 'Käyttäjät Ilmaisilla Palvelimilla', 'stat_allowed_eggs' => 'Sallitut Eggs', 'stat_system_status' => 'Järjestelmän Tila', 'status_on' => 'PÄÄLLÄ', 'status_off' => 'POIS',
    'stats_dashboard_title' => 'Tilastopaneeli', 'stats_total_servers' => 'Palvelimia Yhteensä', 'stats_active_now' => 'Aktiivisia Nyt', 'stats_created_today' => 'Luotu Tänään', 'stats_expiring_soon' => 'Vanhenee Pian (7pv)', 'stats_resources' => 'Resurssit', 'stats_memory' => 'Muisti', 'stats_disk' => 'Levy', 'stats_avg_cpu' => 'Keskim. CPU', 'stats_top_users' => 'Top Käyttäjät', 'stats_no_data' => 'Ei vielä tietoja',
    'section_settings' => 'Asetukset', 'setting_enable_system' => 'Ota Ilmaiset Palvelimet Käyttöön', 'setting_enabled' => 'Käytössä', 'setting_disabled' => 'Poistettu Käytöstä', 'setting_max_servers' => 'Maks. Palvelimia per Käyttäjä', 'setting_description' => 'Palvelimen Kuvaus', 'setting_description_placeholder' => 'Ilmainen Palvelin luotu Free Servers Extension kautta', 'setting_description_help' => 'Tätä kuvausta käytetään jokaisessa luodussa ilmaisessa palvelimessa.', 'setting_display_unit' => 'Resurssien Näyttöyksikkö', 'setting_display_unit_mb' => 'MB (Megatavu)', 'setting_display_unit_gb' => 'GB (Gigatavu)', 'setting_display_unit_help' => 'Valitse miten muisti ja levy näytetään käyttäjille.', 'setting_language' => 'Kieli / Language', 'setting_language_help' => 'Valitse käyttöliittymäkieli kaikille käyttäjille (17 eurooppalaista kieltä tuettu).',
    'section_expiration' => 'Palvelimen Vanheneminen ja Pidennykset', 'setting_expiration_days' => 'Vanhenemispäivät', 'setting_expiration_days_help' => 'Päiviä palvelimen vanhenemiseen (0 = ei vanhene koskaan)', 'setting_extension_days' => 'Pidennyksen Päivät', 'setting_extension_days_help' => 'Päiviä lisätty kun käyttäjä pidentää palvelinta', 'setting_allow_extension' => 'Salli Käyttäjän Pidennykset', 'setting_allow_extension_help' => 'Käyttäjät voivat pidentää vanhenemispäivää', 'yes' => 'Kyllä', 'no' => 'Ei',
    'section_stats' => 'Admin-paneelin Tilastot', 'setting_enable_stats' => 'Ota Tilastopaneeli Käyttöön', 'setting_enable_stats_help' => 'Näytä tilastopaneeli admin-paneelissa',
    'section_discord' => 'Discord Webhook -integraatio', 'setting_discord_webhook' => 'Discord Webhook URL', 'setting_discord_webhook_placeholder' => 'https://discord.com/api/webhooks/...', 'setting_discord_webhook_help' => 'Jätä tyhjäksi poistaaksesi Discord-ilmoitukset käytöstä', 'setting_discord_create' => 'Ilmoita Palvelimen Luonnista', 'setting_discord_delete' => 'Ilmoita Palvelimen Poistosta', 'setting_discord_expire' => 'Ilmoita Palvelimen Vanhenemisesta',
    'section_resources' => 'Oletusresurssit', 'resource_ram' => 'RAM (MB)', 'resource_disk' => 'Levy (MB)', 'resource_cpu' => 'CPU (%)', 'resource_swap' => 'Swap (MB)', 'resource_io' => 'Block IO', 'resource_databases' => 'Tietokannat', 'resource_ports' => 'Portit', 'resource_backups' => 'Varmuuskopiot',
    'section_nodes' => 'Sallitut Solmut', 'nodes_help' => 'Jos solmuja ei ole valittu, kaikki solmut ovat sallittuja.', 'nodes_none' => 'Ei saatavilla olevia solmuja.',
    'btn_save' => 'Tallenna Asetukset', 'btn_add' => 'Lisää', 'btn_enable' => 'Ota Käyttöön', 'btn_disable' => 'Poista Käytöstä', 'btn_remove' => 'Poista',
    'section_eggs' => 'Sallitut Eggs', 'egg_select' => '-- Valitse Egg --', 'egg_custom_name' => 'Mukautettu Nimi', 'egg_status_active' => 'Aktiivinen', 'egg_status_disabled' => 'Poistettu Käytöstä', 'eggs_none' => 'Egg-tiedostoja ei ole lisätty vielä. Lisää egg-tiedostoja yllä tehdäksesi ne saataville ilmaisille palvelimille.', 'eggs_confirm_remove' => 'Poistetaanko tämä egg varmasti?',
    'section_user_limits' => 'Käyttäjäkohtaiset Rajoitukset', 'user_limits_help' => 'Aseta mukautettuja palvelinrajoituksia yksittäisille käyttäjille. Käyttäjät ilman mukautettua rajoitusta käyttävät globaalia rajoitusta (%s).', 'user_search' => 'Etsi Käyttäjää', 'user_search_placeholder' => 'Etsi käyttäjänimellä tai sähköpostilla...', 'user_selected' => 'Valittu Käyttäjä', 'user_no_selected' => 'Ei valittua käyttäjää', 'user_max_servers' => 'Maks. Palvelimia', 'user_add_limit' => 'Lisää Rajoitus', 'table_username' => 'Käyttäjänimi', 'table_email' => 'Sähköposti', 'table_max_servers' => 'Maks. Palvelimia', 'table_current' => 'Nykyinen', 'table_status' => 'Tila', 'table_actions' => 'Toiminnot', 'status_blocked' => 'Estetty', 'status_at_limit' => 'Rajoituksessa', 'status_can_create' => 'Voi Luoda', 'user_limits_none' => 'Ei mukautettuja käyttäjärajoituksia asetettu. Kaikki käyttäjät käyttävät globaalia rajoitusta <strong>%s</strong> palvelimesta.', 'user_has_limit' => 'On Rajoitus', 'user_limit_confirm_remove' => 'Poistetaanko mukautettu rajoitus käyttäjältä %s? He käyttävät globaalia rajoitusta.', 'user_search_no_results' => 'Käyttäjiä ei löydy', 'user_search_error' => 'Virhe käyttäjien haussa', 'user_select_first' => 'Valitse ensin käyttäjä!',
    'alert_db_error' => 'Tietokantatauluja ei löydy. Suorita: php artisan migrate', 'alert_settings_error' => 'Asetuksia ei voitu ladata. Päivitä sivu.', 'msg_success_save' => 'Asetukset tallennettu!', 'msg_error_unknown' => 'Tuntematon toiminto.', 'msg_error_select_egg' => 'Valitse egg!', 'msg_error_egg_exists' => 'Egg on jo olemassa!', 'msg_success_egg_add' => 'Egg lisätty!', 'msg_success_status' => 'Tila muutettu!', 'msg_success_egg_remove' => 'Egg poistettu!', 'msg_error_select_user' => 'Valitse käyttäjä!', 'msg_error_negative' => 'Palvelinten enimmäismäärä ei voi olla negatiivinen!', 'msg_error_user_not_found' => 'Käyttäjää ei löydy!', 'msg_error_limit_exists' => 'Käyttäjällä on jo mukautettu rajoitus!', 'msg_success_limit_set' => 'Mukautettu rajoitus asetettu käyttäjälle %s!', 'msg_error_limit_not_found' => 'Rajoitusta ei löydy!', 'msg_success_limit_update' => 'Rajoitus päivitetty!', 'msg_success_limit_remove' => '%s käyttää nyt globaalia rajoitusta.',
    'api_disabled' => 'Ilmaiset palvelimet ovat tällä hetkellä poissa käytöstä.', 'api_tables_missing' => 'Free Servers -tauluja ei löydy. Suorita php artisan migrate.', 'api_egg_not_available' => 'Tämä egg ei ole saatavilla ilmaisille palvelimille.', 'api_node_not_available' => 'Tämä solmu ei ole saatavilla ilmaisille palvelimille.', 'api_limit_reached' => 'Olet jo saavuttanut ilmaisten palvelimien enimmäismäärän.', 'api_no_ports' => 'Ei vapaita portteja tässä solmussa.', 'api_no_docker' => 'Tälle egg-tiedostolle ei ole määritetty Docker-kuvaa. Ota yhteyttä ylläpitäjään.', 'api_success_create' => 'Palvelin luotu!', 'api_port_taken' => 'Valittu portti oli varattu. Yritä uudelleen.', 'api_error_create' => 'Virhe palvelimen luomisessa: %s', 'api_extension_disabled' => 'Palvelimen pidennys ei ole sallittu.', 'api_server_not_found' => 'Palvelinta ei löydy tai se ei kuulu sinulle.', 'api_success_extend' => 'Palvelinta pidennetty!',
];
