<?php
return [
    'admin_title' => 'Ingyenes Szerverek', 'admin_subtitle' => 'Ingyenes szervereket kínál a felhasználóknak', 'breadcrumb_admin' => 'Admin', 'breadcrumb_extensions' => 'Bővítmények', 'breadcrumb_freeservers' => 'Ingyenes Szerverek',
    'stat_active_servers' => 'Aktív Ingyenes Szerverek', 'stat_users_with_servers' => 'Ingyenes Szerverrel Rendelkező Felhasználók', 'stat_allowed_eggs' => 'Engedélyezett Eggs', 'stat_system_status' => 'Rendszer Állapota', 'status_on' => 'BE', 'status_off' => 'KI',
    'stats_dashboard_title' => 'Statisztikai Irányítópult', 'stats_total_servers' => 'Összes Szerver', 'stats_active_now' => 'Most Aktív', 'stats_created_today' => 'Ma Létrehozva', 'stats_expiring_soon' => 'Hamarosan Lejár (7n)', 'stats_resources' => 'Erőforrások', 'stats_memory' => 'Memória', 'stats_disk' => 'Lemez', 'stats_avg_cpu' => 'Átl. CPU', 'stats_top_users' => 'Top Felhasználók', 'stats_no_data' => 'Még nincs adat',
    'section_settings' => 'Beállítások', 'setting_enable_system' => 'Ingyenes Szerverek Engedélyezése', 'setting_enabled' => 'Engedélyezett', 'setting_disabled' => 'Letiltott', 'setting_max_servers' => 'Max. Szerver Felhasználónként', 'setting_description' => 'Szerver Leírása', 'setting_description_placeholder' => 'Ingyenes Szerver létrehozva a Free Servers Extension által', 'setting_description_help' => 'Ez a leírás minden létrehozott ingyenes szervernél használatos lesz.', 'setting_display_unit' => 'Erőforrás Megjelenítési Egység', 'setting_display_unit_mb' => 'MB (Megabájt)', 'setting_display_unit_gb' => 'GB (Gigabájt)', 'setting_display_unit_help' => 'Válassza meg, hogyan jelenjen meg a memória és a lemez a felhasználóknak.', 'setting_language' => 'Nyelv / Language', 'setting_language_help' => 'Válassza ki a felület nyelvét az összes felhasználó számára (17 európai nyelv támogatott).',
    'section_expiration' => 'Szerver Lejárat és Meghosszabbítás', 'setting_expiration_days' => 'Lejárati Napok', 'setting_expiration_days_help' => 'Napok a szerver lejáratáig (0 = soha nem jár le)', 'setting_extension_days' => 'Meghosszabbítási Napok', 'setting_extension_days_help' => 'Napok hozzáadva amikor a felhasználó meghosszabbítja a szervert', 'setting_allow_extension' => 'Felhasználói Meghosszabbítás Engedélyezése', 'setting_allow_extension_help' => 'A felhasználók meghosszabbíthatják a lejárati dátumot', 'yes' => 'Igen', 'no' => 'Nem',
    'section_stats' => 'Admin Irányítópult Statisztikák', 'setting_enable_stats' => 'Statisztikai Irányítópult Engedélyezése', 'setting_enable_stats_help' => 'Statisztikai irányítópult megjelenítése az admin panelen',
    'section_discord' => 'Discord Webhook Integráció', 'setting_discord_webhook' => 'Discord Webhook URL', 'setting_discord_webhook_placeholder' => 'https://discord.com/api/webhooks/...', 'setting_discord_webhook_help' => 'Hagyja üresen a Discord értesítések letiltásához', 'setting_discord_create' => 'Értesítés Szerver Létrehozáskor', 'setting_discord_delete' => 'Értesítés Szerver Törlésekor', 'setting_discord_expire' => 'Értesítés Szerver Lejáratakor',
    'section_resources' => 'Alapértelmezett Erőforrások', 'resource_ram' => 'RAM (MB)', 'resource_disk' => 'Lemez (MB)', 'resource_cpu' => 'CPU (%)', 'resource_swap' => 'Swap (MB)', 'resource_io' => 'Block IO', 'resource_databases' => 'Adatbázisok', 'resource_ports' => 'Portok', 'resource_backups' => 'Biztonsági Mentések',
    'section_nodes' => 'Engedélyezett Node-ok', 'nodes_help' => 'Ha nincs node kiválasztva, az összes node engedélyezett.', 'nodes_none' => 'Nem érhetők el node-ok.',
    'btn_save' => 'Beállítások Mentése', 'btn_add' => 'Hozzáadás', 'btn_enable' => 'Engedélyezés', 'btn_disable' => 'Letiltás', 'btn_remove' => 'Eltávolítás',
    'section_eggs' => 'Engedélyezett Eggs', 'egg_select' => '-- Egg Kiválasztása --', 'egg_custom_name' => 'Egyéni Név', 'egg_status_active' => 'Aktív', 'egg_status_disabled' => 'Letiltott', 'eggs_none' => 'Még nem adtak hozzá egg-eket. Adjon hozzá egg-eket fentebb az ingyenes szerverekhez való elérhetővé tételükhez.', 'eggs_confirm_remove' => 'Valóban eltávolítja ezt az egg-et?',
    'section_user_limits' => 'Felhasználónkénti Korlátok', 'user_limits_help' => 'Egyéni szerver korlátok beállítása egyes felhasználóknak. Az egyéni korlát nélküli felhasználók a globális korlátot használják (%s).', 'user_search' => 'Felhasználó Keresése', 'user_search_placeholder' => 'Keresés felhasználónév vagy e-mail alapján...', 'user_selected' => 'Kiválasztott Felhasználó', 'user_no_selected' => 'Nincs felhasználó kiválasztva', 'user_max_servers' => 'Max. Szerverek', 'user_add_limit' => 'Korlát Hozzáadása', 'table_username' => 'Felhasználónév', 'table_email' => 'E-mail', 'table_max_servers' => 'Max. Szerverek', 'table_current' => 'Jelenlegi', 'table_status' => 'Állapot', 'table_actions' => 'Műveletek', 'status_blocked' => 'Blokkolt', 'status_at_limit' => 'Korlát Elérve', 'status_can_create' => 'Létrehozhat', 'user_limits_none' => 'Nincsenek egyéni felhasználói korlátok beállítva. Minden felhasználó a globális <strong>%s</strong> szerveres korlátot használja.', 'user_has_limit' => 'Van Korlát', 'user_limit_confirm_remove' => 'Eltávolítja az egyéni korlátot %s számára? A globális korlátot fogja használni.', 'user_search_no_results' => 'Nem találhatók felhasználók', 'user_search_error' => 'Hiba a felhasználók keresése során', 'user_select_first' => 'Kérjük, először válasszon felhasználót!',
    'alert_db_error' => 'Az adatbázis táblák nem találhatók. Kérjük futtassa: php artisan migrate', 'alert_settings_error' => 'A beállítások nem tölthetők be. Kérjük töltse újra az oldalt.', 'msg_success_save' => 'Beállítások sikeresen mentve!', 'msg_error_unknown' => 'Ismeretlen művelet.', 'msg_error_select_egg' => 'Kérjük válasszon egg-et!', 'msg_error_egg_exists' => 'Az egg már létezik!', 'msg_success_egg_add' => 'Egg sikeresen hozzáadva!', 'msg_success_status' => 'Állapot megváltoztatva!', 'msg_success_egg_remove' => 'Egg sikeresen eltávolítva!', 'msg_error_select_user' => 'Kérjük válasszon felhasználót!', 'msg_error_negative' => 'A maximális szerverszám nem lehet negatív!', 'msg_error_user_not_found' => 'Felhasználó nem található!', 'msg_error_limit_exists' => 'A felhasználónak már van egyéni korlátja!', 'msg_success_limit_set' => 'Egyéni korlát beállítva %s számára!', 'msg_error_limit_not_found' => 'Korlát nem található!', 'msg_success_limit_update' => 'Korlát sikeresen frissítve!', 'msg_success_limit_remove' => '%s mostantól a globális korlátot használja.',
    'api_disabled' => 'Az ingyenes szerverek jelenleg le vannak tiltva.', 'api_tables_missing' => 'A Free Servers táblák nem találhatók. Kérjük futtassa: php artisan migrate.', 'api_egg_not_available' => 'Ez az egg nem érhető el ingyenes szerverekhez.', 'api_node_not_available' => 'Ez a node nem érhető el ingyenes szerverekhez.', 'api_limit_reached' => 'Elérte az ingyenes szerverek maximális számát.', 'api_no_ports' => 'Nem áll rendelkezésre szabad port ezen a node-on.', 'api_no_docker' => 'Nincs Docker kép konfigurálva ehhez az egg-hez. Kérjük vegye fel a kapcsolatot egy adminisztrátorral.', 'api_success_create' => 'Szerver sikeresen létrehozva!', 'api_port_taken' => 'A kiválasztott port foglalt lett. Kérjük próbálja újra.', 'api_error_create' => 'Hiba a szerver létrehozásakor: %s', 'api_extension_disabled' => 'A szerver meghosszabbítás nem engedélyezett.', 'api_server_not_found' => 'Szerver nem található vagy nem az Öné.', 'api_success_extend' => 'Szerver sikeresen meghosszabbítva!',
];
