<?php
return [
    'admin_title' => 'Server Gratuiti', 'admin_subtitle' => 'Offri server gratuiti agli utenti', 'breadcrumb_admin' => 'Admin', 'breadcrumb_extensions' => 'Estensioni', 'breadcrumb_freeservers' => 'Server Gratuiti',
    'stat_active_servers' => 'Server Gratuiti Attivi', 'stat_users_with_servers' => 'Utenti con Server Gratuiti', 'stat_allowed_eggs' => 'Eggs Consentiti', 'stat_system_status' => 'Stato del Sistema', 'status_on' => 'ACCESO', 'status_off' => 'SPENTO',
    'stats_dashboard_title' => 'Dashboard Statistiche', 'stats_total_servers' => 'Server Totali', 'stats_active_now' => 'Attivi Ora', 'stats_created_today' => 'Creati Oggi', 'stats_expiring_soon' => 'Scade Presto (7g)', 'stats_resources' => 'Risorse', 'stats_memory' => 'Memoria', 'stats_disk' => 'Disco', 'stats_avg_cpu' => 'CPU Media', 'stats_top_users' => 'Utenti Top', 'stats_no_data' => 'Nessun dato ancora',
    'section_settings' => 'Impostazioni', 'setting_enable_system' => 'Abilita Server Gratuiti', 'setting_enabled' => 'Abilitato', 'setting_disabled' => 'Disabilitato', 'setting_max_servers' => 'Max. Server per Utente', 'setting_description' => 'Descrizione Server', 'setting_description_placeholder' => 'Server Gratuito creato tramite Free Servers Extension', 'setting_description_help' => 'Questa descrizione verrà utilizzata per ogni server gratuito creato.', 'setting_display_unit' => 'Unità di Visualizzazione Risorse', 'setting_display_unit_mb' => 'MB (Megabyte)', 'setting_display_unit_gb' => 'GB (Gigabyte)', 'setting_display_unit_help' => 'Scegli come visualizzare memoria e disco agli utenti.', 'setting_language' => 'Lingua / Language', 'setting_language_help' => 'Scegli la lingua dell\'interfaccia per tutti gli utenti (17 lingue europee supportate).',
    'section_expiration' => 'Scadenza ed Estensioni Server', 'setting_expiration_days' => 'Giorni di Scadenza', 'setting_expiration_days_help' => 'Giorni fino alla scadenza del server (0 = non scade mai)', 'setting_extension_days' => 'Giorni di Estensione', 'setting_extension_days_help' => 'Giorni aggiunti quando l\'utente estende il server', 'setting_allow_extension' => 'Consenti Estensioni Utente', 'setting_allow_extension_help' => 'Gli utenti possono estendere la data di scadenza', 'yes' => 'Sì', 'no' => 'No',
    'section_stats' => 'Statistiche Dashboard Admin', 'setting_enable_stats' => 'Abilita Dashboard Statistiche', 'setting_enable_stats_help' => 'Mostra dashboard statistiche nel pannello admin',
    'section_discord' => 'Integrazione Webhook Discord', 'setting_discord_webhook' => 'URL Webhook Discord', 'setting_discord_webhook_placeholder' => 'https://discord.com/api/webhooks/...', 'setting_discord_webhook_help' => 'Lascia vuoto per disabilitare le notifiche Discord', 'setting_discord_create' => 'Notifica alla Creazione Server', 'setting_discord_delete' => 'Notifica alla Eliminazione Server', 'setting_discord_expire' => 'Notifica alla Scadenza Server',
    'section_resources' => 'Risorse Predefinite', 'resource_ram' => 'RAM (MB)', 'resource_disk' => 'Disco (MB)', 'resource_cpu' => 'CPU (%)', 'resource_swap' => 'Swap (MB)', 'resource_io' => 'Block IO', 'resource_databases' => 'Database', 'resource_ports' => 'Porte', 'resource_backups' => 'Backup',
    'section_nodes' => 'Nodi Consentiti', 'nodes_help' => 'Se non vengono selezionati nodi, tutti i nodi sono consentiti.', 'nodes_none' => 'Nessun nodo disponibile.',
    'btn_save' => 'Salva Impostazioni', 'btn_add' => 'Aggiungi', 'btn_enable' => 'Abilita', 'btn_disable' => 'Disabilita', 'btn_remove' => 'Rimuovi',
    'section_eggs' => 'Eggs Consentiti', 'egg_select' => '-- Seleziona Egg --', 'egg_custom_name' => 'Nome Personalizzato', 'egg_status_active' => 'Attivo', 'egg_status_disabled' => 'Disabilitato', 'eggs_none' => 'Nessun egg aggiunto ancora. Aggiungi eggs sopra per renderli disponibili per i server gratuiti.', 'eggs_confirm_remove' => 'Rimuovere davvero questo egg?',
    'section_user_limits' => 'Limiti per Utente', 'user_limits_help' => 'Imposta limiti server personalizzati per utenti individuali. Gli utenti senza limite personalizzato usano il limite globale (%s).', 'user_search' => 'Cerca Utente', 'user_search_placeholder' => 'Cerca per nome utente o email...', 'user_selected' => 'Utente Selezionato', 'user_no_selected' => 'Nessun utente selezionato', 'user_max_servers' => 'Max. Server', 'user_add_limit' => 'Aggiungi Limite', 'table_username' => 'Nome Utente', 'table_email' => 'Email', 'table_max_servers' => 'Max. Server', 'table_current' => 'Corrente', 'table_status' => 'Stato', 'table_actions' => 'Azioni', 'status_blocked' => 'Bloccato', 'status_at_limit' => 'Al Limite', 'status_can_create' => 'Può Creare', 'user_limits_none' => 'Nessun limite utente personalizzato impostato. Tutti gli utenti usano il limite globale di <strong>%s</strong> server.', 'user_has_limit' => 'Ha Limite', 'user_limit_confirm_remove' => 'Rimuovere limite personalizzato per %s? Useranno il limite globale.', 'user_search_no_results' => 'Nessun utente trovato', 'user_search_error' => 'Errore nella ricerca degli utenti', 'user_select_first' => 'Per favore seleziona prima un utente!',
    'alert_db_error' => 'Tabelle del database non trovate. Per favore esegui: php artisan migrate', 'alert_settings_error' => 'Impossibile caricare le impostazioni. Per favore ricarica la pagina.', 'msg_success_save' => 'Impostazioni salvate con successo!', 'msg_error_unknown' => 'Azione sconosciuta.', 'msg_error_select_egg' => 'Per favore seleziona un egg!', 'msg_error_egg_exists' => 'L\'egg esiste già!', 'msg_success_egg_add' => 'Egg aggiunto con successo!', 'msg_success_status' => 'Stato cambiato!', 'msg_success_egg_remove' => 'Egg rimosso con successo!', 'msg_error_select_user' => 'Per favore seleziona un utente!', 'msg_error_negative' => 'Il massimo di server non può essere negativo!', 'msg_error_user_not_found' => 'Utente non trovato!', 'msg_error_limit_exists' => 'L\'utente ha già un limite personalizzato!', 'msg_success_limit_set' => 'Limite personalizzato impostato per %s!', 'msg_error_limit_not_found' => 'Limite non trovato!', 'msg_success_limit_update' => 'Limite aggiornato con successo!', 'msg_success_limit_remove' => '%s ora usa il limite globale.',
    'api_disabled' => 'I server gratuiti sono attualmente disabilitati.', 'api_tables_missing' => 'Tabelle Free Servers non trovate. Per favore esegui php artisan migrate.', 'api_egg_not_available' => 'Questo egg non è disponibile per i server gratuiti.', 'api_node_not_available' => 'Questo nodo non è disponibile per i server gratuiti.', 'api_limit_reached' => 'Hai già raggiunto il numero massimo di server gratuiti.', 'api_no_ports' => 'Nessuna porta libera disponibile su questo nodo.', 'api_no_docker' => 'Nessuna immagine Docker configurata per questo egg. Per favore contatta un amministratore.', 'api_success_create' => 'Server creato con successo!', 'api_port_taken' => 'La porta selezionata è stata presa. Per favore riprova.', 'api_error_create' => 'Errore nella creazione del server: %s', 'api_extension_disabled' => 'L\'estensione del server non è consentita.', 'api_server_not_found' => 'Server non trovato o non di tua proprietà.', 'api_success_extend' => 'Server esteso con successo!',
];
