<?php
return [
    'admin_title' => 'Gratis Servers', 'admin_subtitle' => 'Bied gebruikers gratis servers aan', 'breadcrumb_admin' => 'Admin', 'breadcrumb_extensions' => 'Extensies', 'breadcrumb_freeservers' => 'Gratis Servers',
    'stat_active_servers' => 'Actieve Gratis Servers', 'stat_users_with_servers' => 'Gebruikers met Gratis Servers', 'stat_allowed_eggs' => 'Toegestane Eggs', 'stat_system_status' => 'Systeemstatus', 'status_on' => 'AAN', 'status_off' => 'UIT',
    'stats_dashboard_title' => 'Statistieken Dashboard', 'stats_total_servers' => 'Totaal Servers', 'stats_active_now' => 'Nu Actief', 'stats_created_today' => 'Vandaag Aangemaakt', 'stats_expiring_soon' => 'Verloopt Binnenkort (7d)', 'stats_resources' => 'Bronnen', 'stats_memory' => 'Geheugen', 'stats_disk' => 'Schijf', 'stats_avg_cpu' => 'Gem. CPU', 'stats_top_users' => 'Top Gebruikers', 'stats_no_data' => 'Nog geen gegevens',
    'section_settings' => 'Instellingen', 'setting_enable_system' => 'Gratis Servers Inschakelen', 'setting_enabled' => 'Ingeschakeld', 'setting_disabled' => 'Uitgeschakeld', 'setting_max_servers' => 'Max. Servers per Gebruiker', 'setting_description' => 'Serverbeschrijving', 'setting_description_placeholder' => 'Gratis Server aangemaakt via Free Servers Extension', 'setting_description_help' => 'Deze beschrijving wordt gebruikt voor elke aangemaakte gratis server.', 'setting_display_unit' => 'Bronweergave-eenheid', 'setting_display_unit_mb' => 'MB (Megabyte)', 'setting_display_unit_gb' => 'GB (Gigabyte)', 'setting_display_unit_help' => 'Kies hoe geheugen en schijf aan gebruikers worden getoond.', 'setting_language' => 'Taal / Language', 'setting_language_help' => 'Kies de interfacetaal voor alle gebruikers (17 Europese talen ondersteund).',
    'section_expiration' => 'Serververlooptijd & Verlengingen', 'setting_expiration_days' => 'Verlooptijddagen', 'setting_expiration_days_help' => 'Dagen tot server verloopt (0 = verloopt nooit)', 'setting_extension_days' => 'Verlengingsdagen', 'setting_extension_days_help' => 'Dagen toegevoegd wanneer gebruiker server verlengt', 'setting_allow_extension' => 'Gebruikersverlengingen Toestaan', 'setting_allow_extension_help' => 'Gebruikers kunnen de verlooptijd verlengen', 'yes' => 'Ja', 'no' => 'Nee',
    'section_stats' => 'Admin Dashboard Statistieken', 'setting_enable_stats' => 'Statistieken Dashboard Inschakelen', 'setting_enable_stats_help' => 'Statistieken dashboard weergeven in admin paneel',
    'section_discord' => 'Discord Webhook Integratie', 'setting_discord_webhook' => 'Discord Webhook URL', 'setting_discord_webhook_placeholder' => 'https://discord.com/api/webhooks/...', 'setting_discord_webhook_help' => 'Leeg laten om Discord meldingen uit te schakelen', 'setting_discord_create' => 'Melden bij Serveraanmaak', 'setting_discord_delete' => 'Melden bij Serververwijdering', 'setting_discord_expire' => 'Melden bij Serververlooptijd',
    'section_resources' => 'Standaard Bronnen', 'resource_ram' => 'RAM (MB)', 'resource_disk' => 'Schijf (MB)', 'resource_cpu' => 'CPU (%)', 'resource_swap' => 'Swap (MB)', 'resource_io' => 'Block IO', 'resource_databases' => 'Databases', 'resource_ports' => 'Poorten', 'resource_backups' => 'Back-ups',
    'section_nodes' => 'Toegestane Nodes', 'nodes_help' => 'Als geen nodes zijn geselecteerd, zijn alle nodes toegestaan.', 'nodes_none' => 'Geen nodes beschikbaar.',
    'btn_save' => 'Instellingen Opslaan', 'btn_add' => 'Toevoegen', 'btn_enable' => 'Inschakelen', 'btn_disable' => 'Uitschakelen', 'btn_remove' => 'Verwijderen',
    'section_eggs' => 'Toegestane Eggs', 'egg_select' => '-- Egg Selecteren --', 'egg_custom_name' => 'Aangepaste Naam', 'egg_status_active' => 'Actief', 'egg_status_disabled' => 'Uitgeschakeld', 'eggs_none' => 'Nog geen eggs toegevoegd. Voeg hierboven eggs toe om ze beschikbaar te maken voor gratis servers.', 'eggs_confirm_remove' => 'Deze egg echt verwijderen?',
    'section_user_limits' => 'Gebruikerslimieten', 'user_limits_help' => 'Stel aangepaste serverlimieten in voor individuele gebruikers. Gebruikers zonder aangepaste limiet gebruiken de globale limiet (%s).', 'user_search' => 'Gebruiker Zoeken', 'user_search_placeholder' => 'Zoeken op gebruikersnaam of e-mail...', 'user_selected' => 'Geselecteerde Gebruiker', 'user_no_selected' => 'Geen gebruiker geselecteerd', 'user_max_servers' => 'Max. Servers', 'user_add_limit' => 'Limiet Toevoegen', 'table_username' => 'Gebruikersnaam', 'table_email' => 'E-mail', 'table_max_servers' => 'Max. Servers', 'table_current' => 'Huidig', 'table_status' => 'Status', 'table_actions' => 'Acties', 'status_blocked' => 'Geblokkeerd', 'status_at_limit' => 'Op Limiet', 'status_can_create' => 'Kan Aanmaken', 'user_limits_none' => 'Geen aangepaste gebruikerslimieten ingesteld. Alle gebruikers gebruiken de globale limiet van <strong>%s</strong> servers.', 'user_has_limit' => 'Heeft Limiet', 'user_limit_confirm_remove' => 'Aangepaste limiet verwijderen voor %s? Ze zullen de globale limiet gebruiken.', 'user_search_no_results' => 'Geen gebruikers gevonden', 'user_search_error' => 'Fout bij zoeken naar gebruikers', 'user_select_first' => 'Selecteer eerst een gebruiker!',
    'alert_db_error' => 'Database tabellen niet gevonden. Voer uit: php artisan migrate', 'alert_settings_error' => 'Instellingen konden niet worden geladen. Herlaad de pagina.', 'msg_success_save' => 'Instellingen succesvol opgeslagen!', 'msg_error_unknown' => 'Onbekende actie.', 'msg_error_select_egg' => 'Selecteer een egg!', 'msg_error_egg_exists' => 'Egg bestaat al!', 'msg_success_egg_add' => 'Egg succesvol toegevoegd!', 'msg_success_status' => 'Status gewijzigd!', 'msg_success_egg_remove' => 'Egg succesvol verwijderd!', 'msg_error_select_user' => 'Selecteer een gebruiker!', 'msg_error_negative' => 'Maximum aantal servers kan niet negatief zijn!', 'msg_error_user_not_found' => 'Gebruiker niet gevonden!', 'msg_error_limit_exists' => 'Gebruiker heeft al een aangepaste limiet!', 'msg_success_limit_set' => 'Aangepaste limiet ingesteld voor %s!', 'msg_error_limit_not_found' => 'Limiet niet gevonden!', 'msg_success_limit_update' => 'Limiet succesvol bijgewerkt!', 'msg_success_limit_remove' => '%s gebruikt nu de globale limiet.',
    'api_disabled' => 'Gratis servers zijn momenteel uitgeschakeld.', 'api_tables_missing' => 'Free Servers tabellen niet gevonden. Voer php artisan migrate uit.', 'api_egg_not_available' => 'Deze egg is niet beschikbaar voor gratis servers.', 'api_node_not_available' => 'Deze node is niet beschikbaar voor gratis servers.', 'api_limit_reached' => 'Je hebt het maximale aantal gratis servers bereikt.', 'api_no_ports' => 'Geen vrije poorten beschikbaar op deze node.', 'api_no_docker' => 'Geen Docker image geconfigureerd voor deze egg. Neem contact op met een beheerder.', 'api_success_create' => 'Server succesvol aangemaakt!', 'api_port_taken' => 'De geselecteerde poort was bezet. Probeer opnieuw.', 'api_error_create' => 'Fout bij aanmaken server: %s', 'api_extension_disabled' => 'Serververlenging is niet toegestaan.', 'api_server_not_found' => 'Server niet gevonden of niet van jou.', 'api_success_extend' => 'Server succesvol verlengd!',
];
