<?php
return [
    'admin_title' => 'Gratis Servere', 'admin_subtitle' => 'Tilby brukere gratis servere', 'breadcrumb_admin' => 'Admin', 'breadcrumb_extensions' => 'Utvidelser', 'breadcrumb_freeservers' => 'Gratis Servere',
    'stat_active_servers' => 'Aktive Gratis Servere', 'stat_users_with_servers' => 'Brukere med Gratis Servere', 'stat_allowed_eggs' => 'Tillatte Eggs', 'stat_system_status' => 'Systemstatus', 'status_on' => 'PÅ', 'status_off' => 'AV',
    'stats_dashboard_title' => 'Statistikkoversikt', 'stats_total_servers' => 'Servere Totalt', 'stats_active_now' => 'Aktive Nå', 'stats_created_today' => 'Opprettet I Dag', 'stats_expiring_soon' => 'Utløper Snart (7d)', 'stats_resources' => 'Ressurser', 'stats_memory' => 'Minne', 'stats_disk' => 'Disk', 'stats_avg_cpu' => 'Gj.sn. CPU', 'stats_top_users' => 'Topp Brukere', 'stats_no_data' => 'Ingen data ennå',
    'section_settings' => 'Innstillinger', 'setting_enable_system' => 'Aktiver Gratis Servere', 'setting_enabled' => 'Aktivert', 'setting_disabled' => 'Deaktivert', 'setting_max_servers' => 'Maks. Servere per Bruker', 'setting_description' => 'Serverbeskrivelse', 'setting_description_placeholder' => 'Gratis Server opprettet via Free Servers Extension', 'setting_description_help' => 'Denne beskrivelsen vil bli brukt for hver opprettet gratis server.', 'setting_display_unit' => 'Ressursvisningsenhet', 'setting_display_unit_mb' => 'MB (Megabyte)', 'setting_display_unit_gb' => 'GB (Gigabyte)', 'setting_display_unit_help' => 'Velg hvordan minne og disk vises til brukere.', 'setting_language' => 'Språk / Language', 'setting_language_help' => 'Velg grensesnittspråk for alle brukere (17 europeiske språk støttes).',
    'section_expiration' => 'Serverutløp og Forlengelser', 'setting_expiration_days' => 'Utløpsdager', 'setting_expiration_days_help' => 'Dager til serveren utløper (0 = utløper aldri)', 'setting_extension_days' => 'Forlengelsesdager', 'setting_extension_days_help' => 'Dager lagt til når brukeren forlenger serveren', 'setting_allow_extension' => 'Tillat Brukerforlengelser', 'setting_allow_extension_help' => 'Brukere kan forlenge utløpsdatoen', 'yes' => 'Ja', 'no' => 'Nei',
    'section_stats' => 'Admin-panelstatistikk', 'setting_enable_stats' => 'Aktiver Statistikkoversikt', 'setting_enable_stats_help' => 'Vis statistikkoversikt i admin-panelet',
    'section_discord' => 'Discord Webhook-integrasjon', 'setting_discord_webhook' => 'Discord Webhook URL', 'setting_discord_webhook_placeholder' => 'https://discord.com/api/webhooks/...', 'setting_discord_webhook_help' => 'La stå tomt for å deaktivere Discord-varsler', 'setting_discord_create' => 'Varsle ved Serveropprettelse', 'setting_discord_delete' => 'Varsle ved Serversletting', 'setting_discord_expire' => 'Varsle ved Serverutløp',
    'section_resources' => 'Standardressurser', 'resource_ram' => 'RAM (MB)', 'resource_disk' => 'Disk (MB)', 'resource_cpu' => 'CPU (%)', 'resource_swap' => 'Swap (MB)', 'resource_io' => 'Block IO', 'resource_databases' => 'Databaser', 'resource_ports' => 'Porter', 'resource_backups' => 'Sikkerhetskopier',
    'section_nodes' => 'Tillatte Noder', 'nodes_help' => 'Hvis ingen noder er valgt, er alle noder tillatt.', 'nodes_none' => 'Ingen noder tilgjengelig.',
    'btn_save' => 'Lagre Innstillinger', 'btn_add' => 'Legg Til', 'btn_enable' => 'Aktiver', 'btn_disable' => 'Deaktiver', 'btn_remove' => 'Fjern',
    'section_eggs' => 'Tillatte Eggs', 'egg_select' => '-- Velg Egg --', 'egg_custom_name' => 'Egendefinert Navn', 'egg_status_active' => 'Aktiv', 'egg_status_disabled' => 'Deaktivert', 'eggs_none' => 'Ingen eggs lagt til ennå. Legg til eggs ovenfor for å gjøre dem tilgjengelige for gratis servere.', 'eggs_confirm_remove' => 'Vil du virkelig fjerne dette egg?',
    'section_user_limits' => 'Grenser per Bruker', 'user_limits_help' => 'Sett egendefinerte servergrenser for individuelle brukere. Brukere uten egendefinert grense bruker den globale grensen (%s).', 'user_search' => 'Søk Bruker', 'user_search_placeholder' => 'Søk etter brukernavn eller e-post...', 'user_selected' => 'Valgt Bruker', 'user_no_selected' => 'Ingen bruker valgt', 'user_max_servers' => 'Maks. Servere', 'user_add_limit' => 'Legg Til Grense', 'table_username' => 'Brukernavn', 'table_email' => 'E-post', 'table_max_servers' => 'Maks. Servere', 'table_current' => 'Nåværende', 'table_status' => 'Status', 'table_actions' => 'Handlinger', 'status_blocked' => 'Blokkert', 'status_at_limit' => 'Ved Grensen', 'status_can_create' => 'Kan Opprette', 'user_limits_none' => 'Ingen egendefinerte brukergrenser angitt. Alle brukere bruker den globale grensen på <strong>%s</strong> servere.', 'user_has_limit' => 'Har Grense', 'user_limit_confirm_remove' => 'Fjern egendefinert grense for %s? De vil bruke den globale grensen.', 'user_search_no_results' => 'Ingen brukere funnet', 'user_search_error' => 'Feil ved søk etter brukere', 'user_select_first' => 'Velg en bruker først!',
    'alert_db_error' => 'Databasetabeller ikke funnet. Kjør: php artisan migrate', 'alert_settings_error' => 'Innstillinger kunne ikke lastes. Vennligst last inn siden på nytt.', 'msg_success_save' => 'Innstillinger lagret!', 'msg_error_unknown' => 'Ukjent handling.', 'msg_error_select_egg' => 'Velg et egg!', 'msg_error_egg_exists' => 'Egg eksisterer allerede!', 'msg_success_egg_add' => 'Egg lagt til!', 'msg_success_status' => 'Status endret!', 'msg_success_egg_remove' => 'Egg fjernet!', 'msg_error_select_user' => 'Velg en bruker!', 'msg_error_negative' => 'Maksimalt antall servere kan ikke være negativt!', 'msg_error_user_not_found' => 'Bruker ikke funnet!', 'msg_error_limit_exists' => 'Brukeren har allerede en egendefinert grense!', 'msg_success_limit_set' => 'Egendefinert grense satt for %s!', 'msg_error_limit_not_found' => 'Grense ikke funnet!', 'msg_success_limit_update' => 'Grense oppdatert!', 'msg_success_limit_remove' => '%s bruker nå den globale grensen.',
    'api_disabled' => 'Gratis servere er for øyeblikket deaktivert.', 'api_tables_missing' => 'Free Servers-tabeller ikke funnet. Kjør php artisan migrate.', 'api_egg_not_available' => 'Dette egg er ikke tilgjengelig for gratis servere.', 'api_node_not_available' => 'Denne noden er ikke tilgjengelig for gratis servere.', 'api_limit_reached' => 'Du har allerede nådd maksimalt antall gratis servere.', 'api_no_ports' => 'Ingen ledige porter tilgjengelig på denne noden.', 'api_no_docker' => 'Ingen Docker-bilde konfigurert for dette egg. Kontakt en administrator.', 'api_success_create' => 'Server opprettet!', 'api_port_taken' => 'Den valgte porten ble tatt. Prøv igjen.', 'api_error_create' => 'Feil ved oppretting av server: %s', 'api_extension_disabled' => 'Serverforlengelse er ikke tillatt.', 'api_server_not_found' => 'Server ikke funnet eller tilhører ikke deg.', 'api_success_extend' => 'Server forlenget!',
];
