<?php
return [
    'admin_title' => 'Darmowe Serwery', 'admin_subtitle' => 'Oferuj użytkownikom darmowe serwery', 'breadcrumb_admin' => 'Admin', 'breadcrumb_extensions' => 'Rozszerzenia', 'breadcrumb_freeservers' => 'Darmowe Serwery',
    'stat_active_servers' => 'Aktywne Darmowe Serwery', 'stat_users_with_servers' => 'Użytkownicy z Darmowymi Serwerami', 'stat_allowed_eggs' => 'Dozwolone Eggs', 'stat_system_status' => 'Status Systemu', 'status_on' => 'WŁĄCZONY', 'status_off' => 'WYŁĄCZONY',
    'stats_dashboard_title' => 'Panel Statystyk', 'stats_total_servers' => 'Serwery Ogółem', 'stats_active_now' => 'Aktywne Teraz', 'stats_created_today' => 'Utworzone Dziś', 'stats_expiring_soon' => 'Wygasa Wkrótce (7d)', 'stats_resources' => 'Zasoby', 'stats_memory' => 'Pamięć', 'stats_disk' => 'Dysk', 'stats_avg_cpu' => 'Średni CPU', 'stats_top_users' => 'Top Użytkownicy', 'stats_no_data' => 'Jeszcze brak danych',
    'section_settings' => 'Ustawienia', 'setting_enable_system' => 'Włącz Darmowe Serwery', 'setting_enabled' => 'Włączony', 'setting_disabled' => 'Wyłączony', 'setting_max_servers' => 'Maks. Serwerów na Użytkownika', 'setting_description' => 'Opis Serwera', 'setting_description_placeholder' => 'Darmowy Serwer utworzony przez Free Servers Extension', 'setting_description_help' => 'Ten opis będzie używany dla każdego utworzonego darmowego serwera.', 'setting_display_unit' => 'Jednostka Wyświetlania Zasobów', 'setting_display_unit_mb' => 'MB (Megabajt)', 'setting_display_unit_gb' => 'GB (Gigabajt)', 'setting_display_unit_help' => 'Wybierz, jak pamięć i dysk są wyświetlane użytkownikom.', 'setting_language' => 'Język / Language', 'setting_language_help' => 'Wybierz język interfejsu dla wszystkich użytkowników (17 europejskich języków obsługiwanych).',
    'section_expiration' => 'Wygasanie i Przedłużenia Serwera', 'setting_expiration_days' => 'Dni Wygaśnięcia', 'setting_expiration_days_help' => 'Dni do wygaśnięcia serwera (0 = nigdy nie wygasa)', 'setting_extension_days' => 'Dni Przedłużenia', 'setting_extension_days_help' => 'Dni dodane gdy użytkownik przedłuża serwer', 'setting_allow_extension' => 'Zezwól na Przedłużenia Użytkownika', 'setting_allow_extension_help' => 'Użytkownicy mogą przedłużać datę wygaśnięcia', 'yes' => 'Tak', 'no' => 'Nie',
    'section_stats' => 'Statystyki Panelu Admina', 'setting_enable_stats' => 'Włącz Panel Statystyk', 'setting_enable_stats_help' => 'Pokaż panel statystyk w panelu admina',
    'section_discord' => 'Integracja Webhooka Discord', 'setting_discord_webhook' => 'URL Webhooka Discord', 'setting_discord_webhook_placeholder' => 'https://discord.com/api/webhooks/...', 'setting_discord_webhook_help' => 'Zostaw puste, aby wyłączyć powiadomienia Discord', 'setting_discord_create' => 'Powiadom przy Tworzeniu Serwera', 'setting_discord_delete' => 'Powiadom przy Usunięciu Serwera', 'setting_discord_expire' => 'Powiadom przy Wygaśnięciu Serwera',
    'section_resources' => 'Domyślne Zasoby', 'resource_ram' => 'RAM (MB)', 'resource_disk' => 'Dysk (MB)', 'resource_cpu' => 'CPU (%)', 'resource_swap' => 'Swap (MB)', 'resource_io' => 'Block IO', 'resource_databases' => 'Bazy Danych', 'resource_ports' => 'Porty', 'resource_backups' => 'Kopie Zapasowe',
    'section_nodes' => 'Dozwolone Nodes', 'nodes_help' => 'Jeśli nie wybrano żadnych nodes, wszystkie nodes są dozwolone.', 'nodes_none' => 'Brak dostępnych nodes.',
    'btn_save' => 'Zapisz Ustawienia', 'btn_add' => 'Dodaj', 'btn_enable' => 'Włącz', 'btn_disable' => 'Wyłącz', 'btn_remove' => 'Usuń',
    'section_eggs' => 'Dozwolone Eggs', 'egg_select' => '-- Wybierz Egg --', 'egg_custom_name' => 'Niestandardowa Nazwa', 'egg_status_active' => 'Aktywny', 'egg_status_disabled' => 'Wyłączony', 'eggs_none' => 'Jeszcze nie dodano eggs. Dodaj eggs powyżej, aby udostępnić je dla darmowych serwerów.', 'eggs_confirm_remove' => 'Naprawdę usunąć ten egg?',
    'section_user_limits' => 'Limity na Użytkownika', 'user_limits_help' => 'Ustaw niestandardowe limity serwerów dla indywidualnych użytkowników. Użytkownicy bez niestandardowego limitu używają globalnego limitu (%s).', 'user_search' => 'Szukaj Użytkownika', 'user_search_placeholder' => 'Szukaj po nazwie użytkownika lub emailu...', 'user_selected' => 'Wybrany Użytkownik', 'user_no_selected' => 'Nie wybrano użytkownika', 'user_max_servers' => 'Maks. Serwerów', 'user_add_limit' => 'Dodaj Limit', 'table_username' => 'Nazwa Użytkownika', 'table_email' => 'Email', 'table_max_servers' => 'Maks. Serwerów', 'table_current' => 'Obecny', 'table_status' => 'Status', 'table_actions' => 'Akcje', 'status_blocked' => 'Zablokowany', 'status_at_limit' => 'Na Limicie', 'status_can_create' => 'Może Tworzyć', 'user_limits_none' => 'Nie ustawiono niestandardowych limitów użytkowników. Wszyscy użytkownicy używają globalnego limitu <strong>%s</strong> serwerów.', 'user_has_limit' => 'Ma Limit', 'user_limit_confirm_remove' => 'Usunąć niestandardowy limit dla %s? Będą używać globalnego limitu.', 'user_search_no_results' => 'Nie znaleziono użytkowników', 'user_search_error' => 'Błąd podczas wyszukiwania użytkowników', 'user_select_first' => 'Proszę najpierw wybrać użytkownika!',
    'alert_db_error' => 'Nie znaleziono tabel bazy danych. Proszę uruchomić: php artisan migrate', 'alert_settings_error' => 'Nie można załadować ustawień. Proszę odświeżyć stronę.', 'msg_success_save' => 'Ustawienia zapisane pomyślnie!', 'msg_error_unknown' => 'Nieznana akcja.', 'msg_error_select_egg' => 'Proszę wybrać egg!', 'msg_error_egg_exists' => 'Egg już istnieje!', 'msg_success_egg_add' => 'Egg dodany pomyślnie!', 'msg_success_status' => 'Status zmieniony!', 'msg_success_egg_remove' => 'Egg usunięty pomyślnie!', 'msg_error_select_user' => 'Proszę wybrać użytkownika!', 'msg_error_negative' => 'Maksymalna liczba serwerów nie może być ujemna!', 'msg_error_user_not_found' => 'Nie znaleziono użytkownika!', 'msg_error_limit_exists' => 'Użytkownik ma już niestandardowy limit!', 'msg_success_limit_set' => 'Ustawiono niestandardowy limit dla %s!', 'msg_error_limit_not_found' => 'Nie znaleziono limitu!', 'msg_success_limit_update' => 'Limit zaktualizowany pomyślnie!', 'msg_success_limit_remove' => '%s używa teraz globalnego limitu.',
    'api_disabled' => 'Darmowe serwery są obecnie wyłączone.', 'api_tables_missing' => 'Nie znaleziono tabel Free Servers. Proszę uruchomić php artisan migrate.', 'api_egg_not_available' => 'Ten egg nie jest dostępny dla darmowych serwerów.', 'api_node_not_available' => 'Ten node nie jest dostępny dla darmowych serwerów.', 'api_limit_reached' => 'Osiągnąłeś już maksymalną liczbę darmowych serwerów.', 'api_no_ports' => 'Brak wolnych portów na tym node.', 'api_no_docker' => 'Brak skonfigurowanego obrazu Docker dla tego egg. Proszę skontaktować się z administratorem.', 'api_success_create' => 'Serwer utworzony pomyślnie!', 'api_port_taken' => 'Wybrany port został zajęty. Proszę spróbować ponownie.', 'api_error_create' => 'Błąd podczas tworzenia serwera: %s', 'api_extension_disabled' => 'Przedłużanie serwera nie jest dozwolone.', 'api_server_not_found' => 'Serwer nie znaleziony lub nie należy do Ciebie.', 'api_success_extend' => 'Serwer przedłużony pomyślnie!',
];
