<?php
return [
    'admin_title' => 'Servidores Gratuitos', 'admin_subtitle' => 'Ofereça servidores gratuitos aos utilizadores', 'breadcrumb_admin' => 'Admin', 'breadcrumb_extensions' => 'Extensões', 'breadcrumb_freeservers' => 'Servidores Gratuitos',
    'stat_active_servers' => 'Servidores Gratuitos Ativos', 'stat_users_with_servers' => 'Utilizadores com Servidores Gratuitos', 'stat_allowed_eggs' => 'Eggs Permitidos', 'stat_system_status' => 'Estado do Sistema', 'status_on' => 'LIGADO', 'status_off' => 'DESLIGADO',
    'stats_dashboard_title' => 'Painel de Estatísticas', 'stats_total_servers' => 'Servidores Totais', 'stats_active_now' => 'Ativos Agora', 'stats_created_today' => 'Criados Hoje', 'stats_expiring_soon' => 'Expira em Breve (7d)', 'stats_resources' => 'Recursos', 'stats_memory' => 'Memória', 'stats_disk' => 'Disco', 'stats_avg_cpu' => 'CPU Média', 'stats_top_users' => 'Melhores Utilizadores', 'stats_no_data' => 'Ainda sem dados',
    'section_settings' => 'Definições', 'setting_enable_system' => 'Ativar Servidores Gratuitos', 'setting_enabled' => 'Ativado', 'setting_disabled' => 'Desativado', 'setting_max_servers' => 'Máx. Servidores por Utilizador', 'setting_description' => 'Descrição do Servidor', 'setting_description_placeholder' => 'Servidor Gratuito criado via Free Servers Extension', 'setting_description_help' => 'Esta descrição será utilizada para cada servidor gratuito criado.', 'setting_display_unit' => 'Unidade de Exibição de Recursos', 'setting_display_unit_mb' => 'MB (Megabyte)', 'setting_display_unit_gb' => 'GB (Gigabyte)', 'setting_display_unit_help' => 'Escolha como a memória e o disco são exibidos aos utilizadores.', 'setting_language' => 'Idioma / Language', 'setting_language_help' => 'Escolha o idioma da interface para todos os utilizadores (17 idiomas europeus suportados).',
    'section_expiration' => 'Expiração e Extensões de Servidor', 'setting_expiration_days' => 'Dias de Expiração', 'setting_expiration_days_help' => 'Dias até o servidor expirar (0 = nunca expira)', 'setting_extension_days' => 'Dias de Extensão', 'setting_extension_days_help' => 'Dias adicionados quando o utilizador estende o servidor', 'setting_allow_extension' => 'Permitir Extensões de Utilizador', 'setting_allow_extension_help' => 'Os utilizadores podem estender a data de expiração', 'yes' => 'Sim', 'no' => 'Não',
    'section_stats' => 'Estatísticas do Painel Admin', 'setting_enable_stats' => 'Ativar Painel de Estatísticas', 'setting_enable_stats_help' => 'Mostrar painel de estatísticas no painel admin',
    'section_discord' => 'Integração Webhook Discord', 'setting_discord_webhook' => 'URL Webhook Discord', 'setting_discord_webhook_placeholder' => 'https://discord.com/api/webhooks/...', 'setting_discord_webhook_help' => 'Deixe vazio para desativar notificações Discord', 'setting_discord_create' => 'Notificar na Criação de Servidor', 'setting_discord_delete' => 'Notificar na Eliminação de Servidor', 'setting_discord_expire' => 'Notificar na Expiração de Servidor',
    'section_resources' => 'Recursos Padrão', 'resource_ram' => 'RAM (MB)', 'resource_disk' => 'Disco (MB)', 'resource_cpu' => 'CPU (%)', 'resource_swap' => 'Swap (MB)', 'resource_io' => 'Block IO', 'resource_databases' => 'Bases de Dados', 'resource_ports' => 'Portas', 'resource_backups' => 'Cópias de Segurança',
    'section_nodes' => 'Nodes Permitidos', 'nodes_help' => 'Se nenhum node for selecionado, todos os nodes são permitidos.', 'nodes_none' => 'Nenhum node disponível.',
    'btn_save' => 'Guardar Definições', 'btn_add' => 'Adicionar', 'btn_enable' => 'Ativar', 'btn_disable' => 'Desativar', 'btn_remove' => 'Remover',
    'section_eggs' => 'Eggs Permitidos', 'egg_select' => '-- Selecionar Egg --', 'egg_custom_name' => 'Nome Personalizado', 'egg_status_active' => 'Ativo', 'egg_status_disabled' => 'Desativado', 'eggs_none' => 'Ainda não foram adicionados eggs. Adicione eggs acima para torná-los disponíveis para servidores gratuitos.', 'eggs_confirm_remove' => 'Realmente remover este egg?',
    'section_user_limits' => 'Limites por Utilizador', 'user_limits_help' => 'Definir limites de servidor personalizados para utilizadores individuais. Utilizadores sem limite personalizado usam o limite global (%s).', 'user_search' => 'Procurar Utilizador', 'user_search_placeholder' => 'Procurar por nome de utilizador ou email...', 'user_selected' => 'Utilizador Selecionado', 'user_no_selected' => 'Nenhum utilizador selecionado', 'user_max_servers' => 'Máx. Servidores', 'user_add_limit' => 'Adicionar Limite', 'table_username' => 'Nome de Utilizador', 'table_email' => 'Email', 'table_max_servers' => 'Máx. Servidores', 'table_current' => 'Atual', 'table_status' => 'Estado', 'table_actions' => 'Ações', 'status_blocked' => 'Bloqueado', 'status_at_limit' => 'No Limite', 'status_can_create' => 'Pode Criar', 'user_limits_none' => 'Nenhum limite de utilizador personalizado definido. Todos os utilizadores usam o limite global de <strong>%s</strong> servidores.', 'user_has_limit' => 'Tem Limite', 'user_limit_confirm_remove' => 'Remover limite personalizado para %s? Usarão o limite global.', 'user_search_no_results' => 'Nenhum utilizador encontrado', 'user_search_error' => 'Erro ao procurar utilizadores', 'user_select_first' => 'Por favor selecione primeiro um utilizador!',
    'alert_db_error' => 'Tabelas da base de dados não encontradas. Por favor execute: php artisan migrate', 'alert_settings_error' => 'Não foi possível carregar as definições. Por favor recarregue a página.', 'msg_success_save' => 'Definições guardadas com sucesso!', 'msg_error_unknown' => 'Ação desconhecida.', 'msg_error_select_egg' => 'Por favor selecione um egg!', 'msg_error_egg_exists' => 'O egg já existe!', 'msg_success_egg_add' => 'Egg adicionado com sucesso!', 'msg_success_status' => 'Estado alterado!', 'msg_success_egg_remove' => 'Egg removido com sucesso!', 'msg_error_select_user' => 'Por favor selecione um utilizador!', 'msg_error_negative' => 'O máximo de servidores não pode ser negativo!', 'msg_error_user_not_found' => 'Utilizador não encontrado!', 'msg_error_limit_exists' => 'O utilizador já tem um limite personalizado!', 'msg_success_limit_set' => 'Limite personalizado definido para %s!', 'msg_error_limit_not_found' => 'Limite não encontrado!', 'msg_success_limit_update' => 'Limite atualizado com sucesso!', 'msg_success_limit_remove' => '%s agora usa o limite global.',
    'api_disabled' => 'Os servidores gratuitos estão atualmente desativados.', 'api_tables_missing' => 'Tabelas Free Servers não encontradas. Por favor execute php artisan migrate.', 'api_egg_not_available' => 'Este egg não está disponível para servidores gratuitos.', 'api_node_not_available' => 'Este node não está disponível para servidores gratuitos.', 'api_limit_reached' => 'Já atingiu o número máximo de servidores gratuitos.', 'api_no_ports' => 'Nenhuma porta livre disponível neste node.', 'api_no_docker' => 'Nenhuma imagem Docker configurada para este egg. Por favor contacte um administrador.', 'api_success_create' => 'Servidor criado com sucesso!', 'api_port_taken' => 'A porta selecionada foi ocupada. Por favor tente novamente.', 'api_error_create' => 'Erro ao criar o servidor: %s', 'api_extension_disabled' => 'A extensão de servidor não é permitida.', 'api_server_not_found' => 'Servidor não encontrado ou não pertence a si.', 'api_success_extend' => 'Servidor estendido com sucesso!',
];
