<?php
return [
    'admin_title' => 'Servere Gratuite', 'admin_subtitle' => 'Oferă utilizatorilor servere gratuite', 'breadcrumb_admin' => 'Admin', 'breadcrumb_extensions' => 'Extensii', 'breadcrumb_freeservers' => 'Servere Gratuite',
    'stat_active_servers' => 'Servere Gratuite Active', 'stat_users_with_servers' => 'Utilizatori cu Servere Gratuite', 'stat_allowed_eggs' => 'Eggs Permise', 'stat_system_status' => 'Stare Sistem', 'status_on' => 'PORNIT', 'status_off' => 'OPRIT',
    'stats_dashboard_title' => 'Panou Statistici', 'stats_total_servers' => 'Total Servere', 'stats_active_now' => 'Active Acum', 'stats_created_today' => 'Create Azi', 'stats_expiring_soon' => 'Expiră Curând (7z)', 'stats_resources' => 'Resurse', 'stats_memory' => 'Memorie', 'stats_disk' => 'Disc', 'stats_avg_cpu' => 'CPU Mediu', 'stats_top_users' => 'Top Utilizatori', 'stats_no_data' => 'Încă fără date',
    'section_settings' => 'Setări', 'setting_enable_system' => 'Activează Servere Gratuite', 'setting_enabled' => 'Activat', 'setting_disabled' => 'Dezactivat', 'setting_max_servers' => 'Max. Servere per Utilizator', 'setting_description' => 'Descriere Server', 'setting_description_placeholder' => 'Server Gratuit creat via Free Servers Extension', 'setting_description_help' => 'Această descriere va fi folosită pentru fiecare server gratuit creat.', 'setting_display_unit' => 'Unitate Afișare Resurse', 'setting_display_unit_mb' => 'MB (Megabyte)', 'setting_display_unit_gb' => 'GB (Gigabyte)', 'setting_display_unit_help' => 'Alege cum sunt afișate memoria și discul utilizatorilor.', 'setting_language' => 'Limbă / Language', 'setting_language_help' => 'Alege limba interfeței pentru toți utilizatorii (17 limbi europene suportate).',
    'section_expiration' => 'Expirare și Prelungiri Server', 'setting_expiration_days' => 'Zile Expirare', 'setting_expiration_days_help' => 'Zile până când serverul expiră (0 = nu expiră niciodată)', 'setting_extension_days' => 'Zile Prelungire', 'setting_extension_days_help' => 'Zile adăugate când utilizatorul prelungește serverul', 'setting_allow_extension' => 'Permite Prelungiri Utilizator', 'setting_allow_extension_help' => 'Utilizatorii pot prelungi data de expirare', 'yes' => 'Da', 'no' => 'Nu',
    'section_stats' => 'Statistici Panou Admin', 'setting_enable_stats' => 'Activează Panou Statistici', 'setting_enable_stats_help' => 'Afișează panoul de statistici în panoul admin',
    'section_discord' => 'Integrare Webhook Discord', 'setting_discord_webhook' => 'URL Webhook Discord', 'setting_discord_webhook_placeholder' => 'https://discord.com/api/webhooks/...', 'setting_discord_webhook_help' => 'Lasă gol pentru a dezactiva notificările Discord', 'setting_discord_create' => 'Notifică la Creare Server', 'setting_discord_delete' => 'Notifică la Ștergere Server', 'setting_discord_expire' => 'Notifică la Expirare Server',
    'section_resources' => 'Resurse Implicite', 'resource_ram' => 'RAM (MB)', 'resource_disk' => 'Disc (MB)', 'resource_cpu' => 'CPU (%)', 'resource_swap' => 'Swap (MB)', 'resource_io' => 'Block IO', 'resource_databases' => 'Baze de Date', 'resource_ports' => 'Porturi', 'resource_backups' => 'Copii de Rezervă',
    'section_nodes' => 'Noduri Permise', 'nodes_help' => 'Dacă nu sunt selectate noduri, toate nodurile sunt permise.', 'nodes_none' => 'Nicio noduri disponibile.',
    'btn_save' => 'Salvează Setările', 'btn_add' => 'Adaugă', 'btn_enable' => 'Activează', 'btn_disable' => 'Dezactivează', 'btn_remove' => 'Elimină',
    'section_eggs' => 'Eggs Permise', 'egg_select' => '-- Selectează Egg --', 'egg_custom_name' => 'Nume Personalizat', 'egg_status_active' => 'Activ', 'egg_status_disabled' => 'Dezactivat', 'eggs_none' => 'Încă nu au fost adăugate eggs. Adaugă eggs mai sus pentru a le face disponibile pentru servere gratuite.', 'eggs_confirm_remove' => 'Chiar elimini acest egg?',
    'section_user_limits' => 'Limite per Utilizator', 'user_limits_help' => 'Setează limite personalizate de servere pentru utilizatori individuali. Utilizatorii fără limită personalizată folosesc limita globală (%s).', 'user_search' => 'Caută Utilizator', 'user_search_placeholder' => 'Caută după nume utilizator sau email...', 'user_selected' => 'Utilizator Selectat', 'user_no_selected' => 'Niciun utilizator selectat', 'user_max_servers' => 'Max. Servere', 'user_add_limit' => 'Adaugă Limită', 'table_username' => 'Nume Utilizator', 'table_email' => 'Email', 'table_max_servers' => 'Max. Servere', 'table_current' => 'Curent', 'table_status' => 'Stare', 'table_actions' => 'Acțiuni', 'status_blocked' => 'Blocat', 'status_at_limit' => 'La Limită', 'status_can_create' => 'Poate Crea', 'user_limits_none' => 'Nicio limită personalizată de utilizator setată. Toți utilizatorii folosesc limita globală de <strong>%s</strong> servere.', 'user_has_limit' => 'Are Limită', 'user_limit_confirm_remove' => 'Elimină limita personalizată pentru %s? Vor folosi limita globală.', 'user_search_no_results' => 'Niciun utilizator găsit', 'user_search_error' => 'Eroare la căutarea utilizatorilor', 'user_select_first' => 'Te rog selectează mai întâi un utilizator!',
    'alert_db_error' => 'Tabelele bazei de date nu au fost găsite. Te rog rulează: php artisan migrate', 'alert_settings_error' => 'Setările nu au putut fi încărcate. Te rog reîncarcă pagina.', 'msg_success_save' => 'Setări salvate cu succes!', 'msg_error_unknown' => 'Acțiune necunoscută.', 'msg_error_select_egg' => 'Te rog selectează un egg!', 'msg_error_egg_exists' => 'Egg-ul există deja!', 'msg_success_egg_add' => 'Egg adăugat cu succes!', 'msg_success_status' => 'Stare schimbată!', 'msg_success_egg_remove' => 'Egg eliminat cu succes!', 'msg_error_select_user' => 'Te rog selectează un utilizator!', 'msg_error_negative' => 'Numărul maxim de servere nu poate fi negativ!', 'msg_error_user_not_found' => 'Utilizator negăsit!', 'msg_error_limit_exists' => 'Utilizatorul are deja o limită personalizată!', 'msg_success_limit_set' => 'Limită personalizată setată pentru %s!', 'msg_error_limit_not_found' => 'Limită negăsită!', 'msg_success_limit_update' => 'Limită actualizată cu succes!', 'msg_success_limit_remove' => '%s folosește acum limita globală.',
    'api_disabled' => 'Serverele gratuite sunt momentan dezactivate.', 'api_tables_missing' => 'Tabelele Free Servers nu au fost găsite. Te rog rulează php artisan migrate.', 'api_egg_not_available' => 'Acest egg nu este disponibil pentru servere gratuite.', 'api_node_not_available' => 'Acest nod nu este disponibil pentru servere gratuite.', 'api_limit_reached' => 'Ai atins deja numărul maxim de servere gratuite.', 'api_no_ports' => 'Niciun port liber disponibil pe acest nod.', 'api_no_docker' => 'Nicio imagine Docker configurată pentru acest egg. Te rog contactează un administrator.', 'api_success_create' => 'Server creat cu succes!', 'api_port_taken' => 'Portul selectat a fost ocupat. Te rog încearcă din nou.', 'api_error_create' => 'Eroare la crearea serverului: %s', 'api_extension_disabled' => 'Prelungirea serverului nu este permisă.', 'api_server_not_found' => 'Server negăsit sau nu îți aparține.', 'api_success_extend' => 'Server prelungit cu succes!',
];
