<?php
return [
    'admin_title' => 'Gratis Servrar', 'admin_subtitle' => 'Erbjud användare gratis servrar', 'breadcrumb_admin' => 'Admin', 'breadcrumb_extensions' => 'Tillägg', 'breadcrumb_freeservers' => 'Gratis Servrar',
    'stat_active_servers' => 'Aktiva Gratis Servrar', 'stat_users_with_servers' => 'Användare med Gratis Servrar', 'stat_allowed_eggs' => 'Tillåtna Eggs', 'stat_system_status' => 'Systemstatus', 'status_on' => 'PÅ', 'status_off' => 'AV',
    'stats_dashboard_title' => 'Statistikpanel', 'stats_total_servers' => 'Totalt Servrar', 'stats_active_now' => 'Aktiva Nu', 'stats_created_today' => 'Skapade Idag', 'stats_expiring_soon' => 'Går Snart Ut (7d)', 'stats_resources' => 'Resurser', 'stats_memory' => 'Minne', 'stats_disk' => 'Disk', 'stats_avg_cpu' => 'Medel CPU', 'stats_top_users' => 'Topp Användare', 'stats_no_data' => 'Ingen data än',
    'section_settings' => 'Inställningar', 'setting_enable_system' => 'Aktivera Gratis Servrar', 'setting_enabled' => 'Aktiverad', 'setting_disabled' => 'Inaktiverad', 'setting_max_servers' => 'Max. Servrar per Användare', 'setting_description' => 'Serverbeskrivning', 'setting_description_placeholder' => 'Gratis Server skapad via Free Servers Extension', 'setting_description_help' => 'Denna beskrivning kommer att användas för varje skapad gratis server.', 'setting_display_unit' => 'Resursvisningsenhet', 'setting_display_unit_mb' => 'MB (Megabyte)', 'setting_display_unit_gb' => 'GB (Gigabyte)', 'setting_display_unit_help' => 'Välj hur minne och disk visas för användare.', 'setting_language' => 'Språk / Language', 'setting_language_help' => 'Välj gränssnittsspråk för alla användare (17 europeiska språk stöds).',
    'section_expiration' => 'Serverutgång & Förlängningar', 'setting_expiration_days' => 'Utgångsdagar', 'setting_expiration_days_help' => 'Dagar tills servern går ut (0 = går aldrig ut)', 'setting_extension_days' => 'Förlängningsdagar', 'setting_extension_days_help' => 'Dagar som läggs till när användaren förlänger servern', 'setting_allow_extension' => 'Tillåt Användarförlängningar', 'setting_allow_extension_help' => 'Användare kan förlänga utgångsdatum', 'yes' => 'Ja', 'no' => 'Nej',
    'section_stats' => 'Admin-panelstatistik', 'setting_enable_stats' => 'Aktivera Statistikpanel', 'setting_enable_stats_help' => 'Visa statistikpanel i admin-panelen',
    'section_discord' => 'Discord Webhook-integration', 'setting_discord_webhook' => 'Discord Webhook URL', 'setting_discord_webhook_placeholder' => 'https://discord.com/api/webhooks/...', 'setting_discord_webhook_help' => 'Lämna tomt för att inaktivera Discord-meddelanden', 'setting_discord_create' => 'Meddela vid Serverskapande', 'setting_discord_delete' => 'Meddela vid Serverborttagning', 'setting_discord_expire' => 'Meddela vid Serverutgång',
    'section_resources' => 'Standardresurser', 'resource_ram' => 'RAM (MB)', 'resource_disk' => 'Disk (MB)', 'resource_cpu' => 'CPU (%)', 'resource_swap' => 'Swap (MB)', 'resource_io' => 'Block IO', 'resource_databases' => 'Databaser', 'resource_ports' => 'Portar', 'resource_backups' => 'Säkerhetskopior',
    'section_nodes' => 'Tillåtna Noder', 'nodes_help' => 'Om inga noder väljs är alla noder tillåtna.', 'nodes_none' => 'Inga noder tillgängliga.',
    'btn_save' => 'Spara Inställningar', 'btn_add' => 'Lägg Till', 'btn_enable' => 'Aktivera', 'btn_disable' => 'Inaktivera', 'btn_remove' => 'Ta Bort',
    'section_eggs' => 'Tillåtna Eggs', 'egg_select' => '-- Välj Egg --', 'egg_custom_name' => 'Anpassat Namn', 'egg_status_active' => 'Aktiv', 'egg_status_disabled' => 'Inaktiverad', 'eggs_none' => 'Inga eggs tillagda än. Lägg till eggs ovan för att göra dem tillgängliga för gratis servrar.', 'eggs_confirm_remove' => 'Verkligen ta bort detta egg?',
    'section_user_limits' => 'Gränser per Användare', 'user_limits_help' => 'Ställ in anpassade servergränser för enskilda användare. Användare utan anpassad gräns använder den globala gränsen (%s).', 'user_search' => 'Sök Användare', 'user_search_placeholder' => 'Sök efter användarnamn eller e-post...', 'user_selected' => 'Vald Användare', 'user_no_selected' => 'Ingen användare vald', 'user_max_servers' => 'Max. Servrar', 'user_add_limit' => 'Lägg Till Gräns', 'table_username' => 'Användarnamn', 'table_email' => 'E-post', 'table_max_servers' => 'Max. Servrar', 'table_current' => 'Nuvarande', 'table_status' => 'Status', 'table_actions' => 'Åtgärder', 'status_blocked' => 'Blockerad', 'status_at_limit' => 'Vid Gränsen', 'status_can_create' => 'Kan Skapa', 'user_limits_none' => 'Inga anpassade användargränser inställda. Alla användare använder den globala gränsen på <strong>%s</strong> servrar.', 'user_has_limit' => 'Har Gräns', 'user_limit_confirm_remove' => 'Ta bort anpassad gräns för %s? De kommer att använda den globala gränsen.', 'user_search_no_results' => 'Inga användare hittades', 'user_search_error' => 'Fel vid sökning efter användare', 'user_select_first' => 'Vänligen välj en användare först!',
    'alert_db_error' => 'Databastabeller hittades inte. Vänligen kör: php artisan migrate', 'alert_settings_error' => 'Inställningar kunde inte laddas. Vänligen ladda om sidan.', 'msg_success_save' => 'Inställningar sparade framgångsrikt!', 'msg_error_unknown' => 'Okänd åtgärd.', 'msg_error_select_egg' => 'Vänligen välj ett egg!', 'msg_error_egg_exists' => 'Egg finns redan!', 'msg_success_egg_add' => 'Egg tillagt framgångsrikt!', 'msg_success_status' => 'Status ändrad!', 'msg_success_egg_remove' => 'Egg borttaget framgångsrikt!', 'msg_error_select_user' => 'Vänligen välj en användare!', 'msg_error_negative' => 'Max antal servrar kan inte vara negativt!', 'msg_error_user_not_found' => 'Användare hittades inte!', 'msg_error_limit_exists' => 'Användaren har redan en anpassad gräns!', 'msg_success_limit_set' => 'Anpassad gräns inställd för %s!', 'msg_error_limit_not_found' => 'Gräns hittades inte!', 'msg_success_limit_update' => 'Gräns uppdaterad framgångsrikt!', 'msg_success_limit_remove' => '%s använder nu den globala gränsen.',
    'api_disabled' => 'Gratis servrar är för närvarande inaktiverade.', 'api_tables_missing' => 'Free Servers-tabeller hittades inte. Vänligen kör php artisan migrate.', 'api_egg_not_available' => 'Detta egg är inte tillgängligt för gratis servrar.', 'api_node_not_available' => 'Denna nod är inte tillgänglig för gratis servrar.', 'api_limit_reached' => 'Du har redan nått det maximala antalet gratis servrar.', 'api_no_ports' => 'Inga lediga portar tillgängliga på denna nod.', 'api_no_docker' => 'Ingen Docker-bild konfigurerad för detta egg. Vänligen kontakta en administratör.', 'api_success_create' => 'Server skapad framgångsrikt!', 'api_port_taken' => 'Den valda porten togs. Vänligen försök igen.', 'api_error_create' => 'Fel vid skapande av server: %s', 'api_extension_disabled' => 'Serverförlängning är inte tillåten.', 'api_server_not_found' => 'Server hittades inte eller ägs inte av dig.', 'api_success_extend' => 'Server förlängd framgångsrikt!',
];
