<?php
return [
    'admin_title' => 'Ücretsiz Sunucular', 'admin_subtitle' => 'Kullanıcılara ücretsiz sunucular sun', 'breadcrumb_admin' => 'Yönetici', 'breadcrumb_extensions' => 'Uzantılar', 'breadcrumb_freeservers' => 'Ücretsiz Sunucular',
    'stat_active_servers' => 'Aktif Ücretsiz Sunucular', 'stat_users_with_servers' => 'Ücretsiz Sunuculu Kullanıcılar', 'stat_allowed_eggs' => 'İzin Verilen Eggs', 'stat_system_status' => 'Sistem Durumu', 'status_on' => 'AÇIK', 'status_off' => 'KAPALI',
    'stats_dashboard_title' => 'İstatistik Paneli', 'stats_total_servers' => 'Toplam Sunucu', 'stats_active_now' => 'Şu An Aktif', 'stats_created_today' => 'Bugün Oluşturulan', 'stats_expiring_soon' => 'Yakında Sona Erecek (7g)', 'stats_resources' => 'Kaynaklar', 'stats_memory' => 'Bellek', 'stats_disk' => 'Disk', 'stats_avg_cpu' => 'Ort. CPU', 'stats_top_users' => 'En İyi Kullanıcılar', 'stats_no_data' => 'Henüz veri yok',
    'section_settings' => 'Ayarlar', 'setting_enable_system' => 'Ücretsiz Sunucuları Etkinleştir', 'setting_enabled' => 'Etkin', 'setting_disabled' => 'Devre Dışı', 'setting_max_servers' => 'Kullanıcı Başına Maks. Sunucu', 'setting_description' => 'Sunucu Açıklaması', 'setting_description_placeholder' => 'Free Servers Uzantısı aracılığıyla oluşturulan Ücretsiz Sunucu', 'setting_description_help' => 'Bu açıklama oluşturulan her ücretsiz sunucu için kullanılacaktır.', 'setting_display_unit' => 'Kaynak Görüntüleme Birimi', 'setting_display_unit_mb' => 'MB (Megabayt)', 'setting_display_unit_gb' => 'GB (Gigabayt)', 'setting_display_unit_help' => 'Bellek ve diskin kullanıcılara nasıl gösterileceğini seçin.', 'setting_language' => 'Dil / Language', 'setting_language_help' => 'Tüm kullanıcılar için arayüz dilini seçin (17 Avrupa dili desteklenmektedir).',
    'section_expiration' => 'Sunucu Sona Erme ve Uzatmalar', 'setting_expiration_days' => 'Sona Erme Günleri', 'setting_expiration_days_help' => 'Sunucunun sona ermesine kadar geçen gün sayısı (0 = asla sona ermez)', 'setting_extension_days' => 'Uzatma Günleri', 'setting_extension_days_help' => 'Kullanıcı sunucuyu uzattığında eklenen günler', 'setting_allow_extension' => 'Kullanıcı Uzatmalarına İzin Ver', 'setting_allow_extension_help' => 'Kullanıcılar sona erme tarihini uzatabilir', 'yes' => 'Evet', 'no' => 'Hayır',
    'section_stats' => 'Yönetici Paneli İstatistikleri', 'setting_enable_stats' => 'İstatistik Panelini Etkinleştir', 'setting_enable_stats_help' => 'Yönetici panelinde istatistik panelini göster',
    'section_discord' => 'Discord Webhook Entegrasyonu', 'setting_discord_webhook' => 'Discord Webhook URL', 'setting_discord_webhook_placeholder' => 'https://discord.com/api/webhooks/...', 'setting_discord_webhook_help' => 'Discord bildirimlerini devre dışı bırakmak için boş bırakın', 'setting_discord_create' => 'Sunucu Oluşturmada Bildir', 'setting_discord_delete' => 'Sunucu Silmede Bildir', 'setting_discord_expire' => 'Sunucu Sona Ermesinde Bildir',
    'section_resources' => 'Varsayılan Kaynaklar', 'resource_ram' => 'RAM (MB)', 'resource_disk' => 'Disk (MB)', 'resource_cpu' => 'CPU (%)', 'resource_swap' => 'Swap (MB)', 'resource_io' => 'Block IO', 'resource_databases' => 'Veritabanları', 'resource_ports' => 'Portlar', 'resource_backups' => 'Yedekler',
    'section_nodes' => 'İzin Verilen Node\'lar', 'nodes_help' => 'Hiçbir node seçilmezse tüm node\'lara izin verilir.', 'nodes_none' => 'Kullanılabilir node yok.',
    'btn_save' => 'Ayarları Kaydet', 'btn_add' => 'Ekle', 'btn_enable' => 'Etkinleştir', 'btn_disable' => 'Devre Dışı Bırak', 'btn_remove' => 'Kaldır',
    'section_eggs' => 'İzin Verilen Eggs', 'egg_select' => '-- Egg Seç --', 'egg_custom_name' => 'Özel Ad', 'egg_status_active' => 'Aktif', 'egg_status_disabled' => 'Devre Dışı', 'eggs_none' => 'Henüz egg eklenmedi. Ücretsiz sunucular için kullanılabilir hale getirmek üzere yukarıdan egg ekleyin.', 'eggs_confirm_remove' => 'Bu egg gerçekten kaldırılsın mı?',
    'section_user_limits' => 'Kullanıcı Başına Limitler', 'user_limits_help' => 'Bireysel kullanıcılar için özel sunucu limitleri ayarlayın. Özel limiti olmayan kullanıcılar global limiti kullanır (%s).', 'user_search' => 'Kullanıcı Ara', 'user_search_placeholder' => 'Kullanıcı adı veya e-posta ile ara...', 'user_selected' => 'Seçili Kullanıcı', 'user_no_selected' => 'Kullanıcı seçilmedi', 'user_max_servers' => 'Maks. Sunucu', 'user_add_limit' => 'Limit Ekle', 'table_username' => 'Kullanıcı Adı', 'table_email' => 'E-posta', 'table_max_servers' => 'Maks. Sunucu', 'table_current' => 'Mevcut', 'table_status' => 'Durum', 'table_actions' => 'Eylemler', 'status_blocked' => 'Engellendi', 'status_at_limit' => 'Limitde', 'status_can_create' => 'Oluşturabilir', 'user_limits_none' => 'Özel kullanıcı limiti ayarlanmadı. Tüm kullanıcılar <strong>%s</strong> sunucunun global limitini kullanır.', 'user_has_limit' => 'Limit Var', 'user_limit_confirm_remove' => '%s için özel limit kaldırılsın mı? Global limiti kullanacaklar.', 'user_search_no_results' => 'Kullanıcı bulunamadı', 'user_search_error' => 'Kullanıcı aramasında hata', 'user_select_first' => 'Lütfen önce bir kullanıcı seçin!',
    'alert_db_error' => 'Veritabanı tabloları bulunamadı. Lütfen çalıştırın: php artisan migrate', 'alert_settings_error' => 'Ayarlar yüklenemedi. Lütfen sayfayı yenileyin.', 'msg_success_save' => 'Ayarlar başarıyla kaydedildi!', 'msg_error_unknown' => 'Bilinmeyen eylem.', 'msg_error_select_egg' => 'Lütfen bir egg seçin!', 'msg_error_egg_exists' => 'Egg zaten mevcut!', 'msg_success_egg_add' => 'Egg başarıyla eklendi!', 'msg_success_status' => 'Durum değiştirildi!', 'msg_success_egg_remove' => 'Egg başarıyla kaldırıldı!', 'msg_error_select_user' => 'Lütfen bir kullanıcı seçin!', 'msg_error_negative' => 'Maksimum sunucu sayısı negatif olamaz!', 'msg_error_user_not_found' => 'Kullanıcı bulunamadı!', 'msg_error_limit_exists' => 'Kullanıcının zaten özel bir limiti var!', 'msg_success_limit_set' => '%s için özel limit ayarlandı!', 'msg_error_limit_not_found' => 'Limit bulunamadı!', 'msg_success_limit_update' => 'Limit başarıyla güncellendi!', 'msg_success_limit_remove' => '%s artık global limiti kullanıyor.',
    'api_disabled' => 'Ücretsiz sunucular şu anda devre dışı.', 'api_tables_missing' => 'Free Servers tabloları bulunamadı. Lütfen php artisan migrate çalıştırın.', 'api_egg_not_available' => 'Bu egg ücretsiz sunucular için mevcut değil.', 'api_node_not_available' => 'Bu node ücretsiz sunucular için mevcut değil.', 'api_limit_reached' => 'Maksimum ücretsiz sunucu sayısına ulaştınız.', 'api_no_ports' => 'Bu node\'da boş port yok.', 'api_no_docker' => 'Bu egg için Docker görüntüsü yapılandırılmamış. Lütfen bir yöneticiyle iletişime geçin.', 'api_success_create' => 'Sunucu başarıyla oluşturuldu!', 'api_port_taken' => 'Seçilen port alındı. Lütfen tekrar deneyin.', 'api_error_create' => 'Sunucu oluşturmada hata: %s', 'api_extension_disabled' => 'Sunucu uzatmaya izin verilmiyor.', 'api_server_not_found' => 'Sunucu bulunamadı veya size ait değil.', 'api_success_extend' => 'Sunucu başarıyla uzatıldı!',
];
